/**
 * 自然拼读拆分数据（由 tools/generate_phonics_ai.py 用 AI 生成，勿手改）
 * 每个条目：wordId → 拆分字符串（段间用 - 连接，短语间用空格连接）
 * 例如: hello → he-llo, fantastic → fan-tas-tic
 */
const PHONICS = {
  "ancient": "an-ci-ent",
  "camp": "camp",
  "landscape": "land-scape",
  "strange": "strange",
  "vacation": "va-ca-tion",
  "fantastic": "fan-tas-tic",
  "town": "town",
  "breath": "breath",
  "take_sb_s_breath_away": "take sb’s breath away",
  "especially": "es-pe-cial-ly",
  "steamed_chicken_soup": "steamed chicken soup",
  "anywhere": "an-y-where",
  "nothing": "noth-ing",
  "guide": "guide",
  "scenery": "scen-er-y",
  "silk": "silk",
  "scarf": "scarf",
  "ready": "ready",
  "ready_to_do_sth": "ready to do sth",
  "somewhere": "some-where",
  "myself": "my-self",
  "nothing_but": "nothing but",
  "hotel": "hotel",
  "comfortable": "com-fort-a-ble",
  "bored": "bored",
  "sky": "sky",
  "towards": "tow-ards",
  "rainbow": "rain-bow",
  "square": "square",
  "during": "dur-ing",
  "victory": "vic-tor-y",
  "russian": "Rus-si-an",
  "fight": "fight",
  "against": "a-gainst",
  "fight_against_sb_sth": "fight against sb / sth",
  "artwork": "art-work",
  "thousands_of": "thou-sands of",
  "tear": "tear",
  "remind": "re-mind",
  "peace": "peace",
  "easily": "e-a-si-ly",
  "forget": "for-get",
  "noon": "noon",
  "sick": "sick",
  "metro": "me-tro",
  "station": "sta-tion",
  "palace": "pal-ace",
  "accordion": "ac-cor-dion",
  "get_together": "get together",
  "in_the_sun": "in the sun",
  "tower": "tow-er",
  "might": "might",
  "budget": "bud-get",
  "passport": "pas-sport",
  "forgetful": "for-get-ful",
  "faraway": "far-a-way",
  "regular": "reg-u-lar",
  "countryside": "coun-try-side",
  "turn_around": "turn a-round",
  "surprised": "sur-prised",
  "deer": "deer",
  "probably": "prob-a-bly",
  "look_for": "look-for",
  "guest_greeting_pine": "Guest-Greet-ing-Pine",
  "sea_of_clouds": "Sea-of-Clouds",
  "seattle": "Seattle",
  "red_square": "Red-Square",
  "alexander_garden": "Alex-an-der-Gar-den",
  "vincent": "Vin-cent",
  "moscow": "Mos-cow",
  "russia": "Rus-si-a",
  "the_victory_museum": "the-Vic-to-ry-Muse-um",
  "nazi": "Nazi",
  "world_war_ii": "World-War-II",
  "moscow_metro": "Mos-cow-Me-tro",
  "scotland": "Scot-land",
  "pack": "pack",
  "pack_up": "pack-up",
  "bathroom": "bath-room",
  "sort": "sort",
  "bedroom": "bed-room",
  "balcony": "bal-con-y",
  "hang_up": "hang-up",
  "invite": "in-vite",
  "living_room": "liv-ing-room",
  "arrival": "ar-rival",
  "yet": "yet",
  "add": "add",
  "add_sth_to_sth": "add-sth-to-sth",
  "go_shopping": "go-shop-ping",
  "biscuit": "biscuit",
  "borrow": "bor-row",
  "plan": "plan",
  "treasure": "treas-ure",
  "hunt": "hunt",
  "treasure_hunt": "treas-ure hunt",
  "lift": "lift",
  "give_sb_a_lift": "give sb a lift",
  "until": "until",
  "be_careful_with": "be care-ful with",
  "movie": "movie",
  "the_movies": "the movies",
  "dead": "dead",
  "note": "note",
  "take_notes": "take notes",
  "clean_up": "clean up",
  "community": "com-mu-ni-ty",
  "rubbish": "rubb-ish",
  "almost": "al-most",
  "journey": "jour-ney",
  "pull": "pull",
  "luggage": "lug-ga-ge",
  "ah": "ah",
  "share_sth_with_sb": "share sth with sb",
  "mm": "mm",
  "familiar": "fa-mi-li-ar",
  "joke": "joke",
  "several": "sev-er-al",
  "nod": "nod",
  "writer": "writ-er",
  "text": "text",
  "describe": "de-scribe",
  "wherever": "where-ver",
  "matter": "mat-ter",
  "no_matter": "no mat-ter",
  "perhaps": "per-haps",
  "plate": "plate",
  "freshly": "fresh-ly",
  "smell": "smell",
  "joy": "joy",
  "apartment": "ap-art-ment",
  "block": "block",
  "decorate": "de-cor-ate",
  "cover": "cov-er",
  "poster": "post-er",
  "scissors": "scis-sors",
  "glue": "glue",
  "paper_cut": "pa-per-cut",
  "compare": "com-pare",
  "shy": "shy",
  "lazy": "lazy",
  "loud": "loud",
  "outgoing": "out-go-ing",
  "hard_working": "hard-work-ing",
  "perform": "per-form",
  "alone": "a-lone",
  "solve": "solve",
  "flute": "flute",
  "congratulation": "con-gra-tu-la-tion",
  "congratulations_on": "con-gra-tu-la-tions on",
  "prize": "prize",
  "attend": "at-tend",
  "as_as": "as … as …",
  "besides": "be-side-s",
  "spare": "spare",
  "spare_time": "spare time",
  "pleasure": "plea-sure",
  "have_sth_in_common": "have sth in com-mon",
  "appearance": "ap-pear-ance",
  "personality": "per-son-al-i-ty",
  "serious": "ser-i-ous",
  "strength": "strength",
  "slim": "slim",
  "fact": "fact",
  "population": "pop-u-la-tion",
  "km": "km",
  "average": "av-er-age",
  "rainfall": "rain-fall",
  "per": "per",
  "pleasant": "ple-as-ant",
  "difference": "dif-fer-ence",
  "alike": "a-like",
  "mirror": "mirror",
  "interest": "in-ter-est",
  "novel": "nov-el",
  "sense": "sense",
  "humour": "hu-mour",
  "thanks_to": "thanks to",
  "opinion": "op-in-ion",
  "make_a_mistake": "make a mis-take",
  "less": "less",
  "straightforward": "straight-for-ward",
  "honest": "hon-est",
  "direct": "di-rect",
  "similarity": "sim-i-lar-i-ty",
  "friendship": "friend-ship",
  "metre": "met-re",
  "prince": "prin-ce",
  "character": "char-ac-ter",
  "pauper": "pau-per",
  "exchange": "ex-change",
  "accident": "ac-ci-dent",
  "by_accident": "by ac-ci-dent",
  "expect": "ex-pect",
  "silver": "sil-ver",
  "lining": "lin-ing",
  "silver_lining": "sil-ver lin-ing",
  "situation": "sit-u-a-tion",
  "care_about": "care a-bout",
  "reach": "reach",
  "reach_for": "reach for",
  "touch": "touch",
  "lend_sb_a_hand": "lend (sb) a hand",
  "julie": "Julie",
  "vancouver": "Van-cou-ver",
  "matt": "Matt",
  "stephen": "Step-hen",
  "diana": "Dian-a",
  "edward": "Ed-ward",
  "mark_twain": "Mark Twain",
  "rose": "Rose",
  "moss": "moss",
  "redwood": "red-wood",
  "cheetah": "chee-tah",
  "folding": "fold-ing",
  "folding_fan": "folding fan",
  "bamboo": "bam-boo",
  "yeah": "yeah",
  "popular": "pop-u-lar",
  "goodness": "good-ness",
  "tool": "tool",
  "actually": "ac-tu-al-ly",
  "shoot": "shoot",
  "appear": "ap-pear",
  "feel_free_to_do_sth": "feel free (to do sth)",
  "land": "land",
  "african": "African",
  "peony": "peony",
  "lotus": "lo-tus",
  "butterfly": "but-ter-fly",
  "wing": "wing",
  "frog": "frog",
  "up_to": "up to",
  "weigh": "weigh",
  "kg": "kg",
  "ginkgo": "gin-kgo",
  "believe": "be-lieve",
  "province": "pro-vince",
  "take_a_walk": "take a walk",
  "connect": "con-nect",
  "connected": "con-nec-ted",
  "be_connected_with_to": "be connected with / to",
  "without": "with-out",
  "imagine": "im-ag-ine",
  "honey": "honey",
  "disappointed": "dis-ap-point-ed",
  "connection": "con-nec-tion",
  "pollination": "pol-li-na-tion",
  "pollen": "pol-len",
  "action": "ac-tion",
  "in_fact": "in fact",
  "per_cent": "per cent",
  "for_this_reason": "for this reason",
  "planet": "plan-et",
  "in_order_to": "in order to",
  "store": "store",
  "honeycomb": "honey-comb",
  "communicate": "com-mu-ni-cate",
  "play_a_part_in_sth": "play a part (in sth)",
  "ecosystem": "e-co-sys-tem",
  "protect": "pro-tect",
  "importance": "im-por-tance",
  "title": "ti-tle",
  "human": "hu-man",
  "ant": "ant",
  "be_home_to_sb_sth": "be home to sb / sth",
  "happiness": "hap-pi-ness",
  "disappoint": "dis-ap-point",
  "mushroom": "mush-room",
  "ton": "ton",
  "role": "ro-le",
  "play_a_role_in": "play a role (in)",
  "pea": "pea",
  "climate": "cli-mate",
  "ocean": "o-cean",
  "except": "ex-cept",
  "tiny": "tin-y",
  "lively": "liv-ely",
  "the_arctic_ocean": "the Arctic Ocean",
  "billy": "Billy",
  "pepper": "pep-per",
  "cut_up": "cut up",
  "mix": "mix",
  "bake": "bake",
  "oven": "o-ven",
  "pour_sth_into_sth": "pour sth into sth",
  "flour": "flour",
  "boil": "boil",
  "butter": "but-ter",
  "cheese": "cheese",
  "cut_sth_in_into_sth": "cut sth in / into sth",
  "tablespoon": "table-spoon",
  "mash": "mash",
  "mashed_potatoes": "mashed potatoes",
  "stir_fry": "stir-fry",
  "do_with": "do with",
  "bowl": "bowl",
  "heat": "heat",
  "oil": "oil",
  "pan": "pan",
  "put_sth_back": "put sth back",
  "mix_with": "mix with",
  "simple": "simple",
  "ingredient": "in-gre-di-ent",
  "instruction": "in-struc-tion",
  "steamed_fish": "steamed fish",
  "sour": "sour",
  "hot_and_sour_soup": "hot and sour soup",
  "mess": "mess",
  "pretty": "pre-tty",
  "christmas": "Christ-mas",
  "pancake": "pan-cake",
  "dream": "dream",
  "university": "un-i-ver-si-ty",
  "go_boating": "go boating",
  "memory": "mem-o-ry",
  "visible": "vis-i-ble",
  "along_with_sb_sth": "along with sb / sth",
  "pumpkin": "pump-kin",
  "pie": "pie",
  "warm_up": "warm up",
  "cinnamon": "cin-na-mon",
  "fill_with": "fill with",
  "sweetness": "sweet-ness",
  "college": "col-lege",
  "host": "host",
  "hostess": "host-ess",
  "recipe": "re-ci-pe",
  "cream": "cream",
  "crust": "crust",
  "mixture": "mix-ture",
  "least": "least",
  "at_least": "at least",
  "secret": "sec-ret",
  "according_to": "according to",
  "whenever": "whenever",
  "item": "item",
  "spaghetti": "spag-het-ti",
  "spoon": "spoon",
  "slice": "slice",
  "couple": "cou-ple",
  "island": "is-land",
  "wife": "wife",
  "separate": "se-pa-rate",
  "born": "born",
  "one_by_one": "one by one",
  "thanksgiving": "Thanksgiving",
  "guoqiao_rice_noodles": "Guoqiao Rice Noodles",
  "yourself": "your-self",
  "engineer": "en-gi-neer",
  "fashion": "fash-ion",
  "designer": "de-sign-er",
  "director": "di-rec-tor",
  "musician": "mu-si-cian",
  "fireman": "fire-man",
  "ai": "AI",
  "essay": "es-say",
  "classic": "class-ic",
  "keep_on_doing_sth": "keep on doing sth",
  "make_sure": "make sure",
  "try_one_s_best": "try one’s best",
  "literature": "lit-er-a-ture",
  "athlete": "ath-le-te",
  "photographer": "pho-tog-ra-pher",
  "painter": "paint-er",
  "businessman": "bus-i-ness-man",
  "actress": "ac-tress",
  "lawyer": "law-yer",
  "law": "law",
  "bath": "bath",
  "miss": "miss",
  "be_tired_of": "be tired of",
  "able": "a-ble",
  "stick": "stick",
  "stick_to_sth": "stick to sth",
  "resolution": "re-sol-ution",
  "have_to_do_with_sb_sth": "have (…) to do with sb / sth",
  "mini_goal": "mini-goal",
  "achieve": "ach-ieve",
  "physical": "phys-i-cal",
  "health": "health",
  "healthily": "health-i-ly",
  "take_up": "take up",
  "photography": "pho-tog-ra-phy",
  "self_improvement": "self-improvement",
  "confident": "con-fi-dent",
  "organized": "or-ga-nized",
  "wisely": "wis-e-ly",
  "possible": "pos-si-ble",
  "paragraph": "par-a-graph",
  "introduce": "in-tro-duce",
  "meaning": "mean-ing",
  "fail": "fail",
  "ahead": "a-head",
  "put_out": "put out",
  "design": "de-sign",
  "bridge": "bridge",
  "final": "fi-nal",
  "confidence": "con-fi-dence",
  "draw_to_a_close": "draw to a close",
  "form": "form",
  "relationship": "re-la-tion-ship",
  "push_up": "push-up",
  "energetic": "en-er-get-ic",
  "last_but_not_least": "last but not least",
  "jason": "Jason",
  "tina": "Tina",
  "prediction": "pre-dic-tion",
  "outer": "out-er",
  "outer_space": "outer space",
  "worse": "wor-se",
  "take_over": "take over",
  "sci_fi": "sci-fi",
  "ticket": "tick-et",
  "positive": "pos-i-tive",
  "traffic": "traf-fic",
  "technology": "tech-nol-o-gy",
  "video": "vid-e-o",
  "transport": "trans-port",
  "system": "sys-tem",
  "efficient": "ef-fi-cient",
  "education": "ed-u-ca-tion",
  "length": "length",
  "topic": "top-ic",
  "partner": "partner",
  "shall": "shall",
  "pass": "pass",
  "winner": "win-ner",
  "cure": "cure",
  "cancer": "can-cer",
  "concert": "con-cert",
  "cash": "cash",
  "wallet": "wal-let",
  "guest": "guest",
  "chief": "chief",
  "researcher": "re-search-er",
  "research": "re-search",
  "futurist": "fu-tur-ist",
  "everywhere": "everywhere",
  "robotics": "ro-bot-ics",
  "industry": "in-dus-try",
  "service": "ser-vice",
  "disaster": "dis-as-ter",
  "emergency": "em-er-gen-cy",
  "disappear": "dis-ap-pear",
  "challenging": "chal-leng-ing",
  "pilot": "pi-lot",
  "expert": "ex-pert",
  "replace": "re-place",
  "creativity": "cre-a-tiv-ity",
  "emotional": "e-mo-tion-al",
  "intelligence": "in-tel-li-gence",
  "emotional_intelligence": "e-mo-tion-al in-tel-li-gence",
  "mention": "men-tion",
  "refrigerator": "ref-ri-ger-a-tor",
  "low": "low",
  "run_low_on_sth": "run low (on sth)",
  "accept": "ac-cept",
  "influence": "in-flu-ence",
  "creative": "cre-a-tive",
  "impossible": "im-pos-si-ble",
  "quality": "qual-i-ty",
  "develop": "de-vel-op",
  "german": "ger-man",
  "valuable": "val-u-a-ble",
  "public": "pub-lic",
  "medical": "med-i-cal",
  "challenge": "chal-lenge",
  "task": "task",
  "depend": "de-pend",
  "depend_on_upon": "de-pend on up-on",
  "come_over": "come o-ver",
  "as_long_as": "as long as",
  "jennifer": "jen-ni-fer",
  "harry": "har-ry",
  "asimov": "a-si-mov",
  "france": "france",
  "mandy": "man-dy",
  "communication": "com-mu-ni-ca-tion",
  "face_to_face": "face to face",
  "text_message": "text message",
  "sign": "sign",
  "speaker": "spea-ker",
  "rehearsal": "re-hear-sal",
  "show_sb_around": "show sb around",
  "local": "lo-cal",
  "u8_face_to_face": "face-to-face",
  "professor": "pro-fes-sor",
  "speech": "speech",
  "argue": "ar-gue",
  "make_up_with_sb": "make up (with sb)",
  "in_person": "in person",
  "prefer": "prefer",
  "calm": "calm",
  "worry_about": "worry about",
  "expression": "ex-pres-sion",
  "chance": "chance",
  "meeting": "meet-ing",
  "difficulty": "dif-fi-cul-ty",
  "right_away": "right away",
  "line": "line",
  "drop_sb_a_line": "drop sb a line",
  "detail": "de-tail",
  "reunion": "re-u-nion",
  "seriously": "ser-i-ous-ly",
  "training": "train-ing",
  "nervous": "ner-vous",
  "stranger": "stran-ger",
  "tip": "tip",
  "carefully": "care-ful-ly",
  "show_interest_in_sth": "show in-ter-est in sth",
  "listener": "lis-ten-er",
  "point": "point",
  "surely": "sure-ly",
  "continue": "con-tin-ue",
  "impolite": "im-po-lite",
  "personal": "per-son-al",
  "argue_with_sb": "ar-gue with sb",
  "move_on_to_sth": "move on (to sth)",
  "sincere": "sin-cere",
  "find_out": "find out",
  "pay": "pay",
  "attention": "at-ten-tion",
  "pay_attention_to": "pay at-ten-tion (to ...)",
  "be_yourself": "be your-self",
  "offer": "of-fer",
  "reasonable": "re-a-son-a-ble",
  "social": "so-cial",
  "medium": "me-di-um",
  "social_media": "so-cial me-di-a",
  "trust": "trust",
  "keep_away_from": "keep ( ... ) a-way from ...",
  "misunderstanding": "mis-un-der-stand-ing",
  "event": "e-vent",
  "take_place": "take place",
  "cost": "cost",
  "opportunity": "op-por-tu-ni-ty",
  "benefit": "be-ne-fit",
  "benefit_from": "be-ne-fit ( ... ) from ( ... )",
  "reply": "reply",
  "honour": "hon-our",
  "sincerely": "sin-cer-e-ly",
  "opening": "open-ing",
  "closing": "clo-sing",
  "sentence": "sen-tence",
  "date": "date",
  "clause": "clau-se",
  "susan": "Susan",
  "jones": "Jones",
  "game": "game",
  "excited": "ex-cit-ed",
  "sleep": "sleep",
  "worry": "wor-ry",
  "autumn": "au-tumn",
  "train": "train",
  "beside": "be-side",
  "sweep": "sweep",
  "floor": "floor",
  "toilet": "to-i-let",
  "careful": "care-ful",
  "tomorrow": "tom-or-row",
  "face": "face",
  "kitchen": "kit-chen",
  "word": "word",
  "slow": "slow",
  "fan": "fan",
  "earth": "earth",
  "bee": "bee",
  "far": "far",
  "meat": "meat",
  "grape": "grape",
  "thin": "thin",
  "worker": "work-er",
  "fire": "fire",
  "helpful": "help-ful"
};

window.PHONICS = PHONICS;
