#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''
为八年级上册英语词库自动生成助记字段（emoji / 词根 / 联想 / 例句）。
准确性原则：不确定的词根不强行拆解；例句用最简句型。

用法：
  cd "E:\coding-zhou\AI 编程\记单词工具"
  python -X utf8 tools/enrich_dict.py
'''
import re, sys

sys.stdout.reconfigure(encoding='utf-8')

# ============================================================
# 一、Emoji 映射
# ============================================================
EMOJI = {}
_raw_emoji = {
    'ancient': '\U0001f3db\ufe0f', 'camp': '\u26fa', 'landscape': '\U0001f3de\ufe0f',
    'strange': '\u2753', 'vacation': '\U0001f3d6\ufe0f', 'fantastic': '\U0001f929',
    'town': '\U0001f3d8\ufe0f', 'breath': '\U0001f32c\ufe0f', 'anywhere': '\U0001f30d',
    'nothing': '\U0001f6ab', 'guide': '\U0001f9ed', 'scenery': '\U0001f304\ufe0f',
    'silk': '\U0001f9f5', 'scarf': '\U0001f9e3', 'ready': '\u2705',
    'somewhere': '\U0001f4cd', 'myself': '\U0001fa9e', 'hotel': '\U0001f3e8',
    'comfortable': '\U0001f60c', 'bored': '\U0001f611', 'sky': '\U0001f324\ufe0f',
    'rainbow': '\U0001f308', 'square': '\u2b1c', 'during': '\u23f3',
    'victory': '\U0001f3c6', 'fight': '\U0001f94a', 'tear': '\U0001f4a7',
    'remind': '\U0001f514', 'peace': '\U0001f54a\ufe0f', 'easily': '\U0001f4a8',
    'forget': '\U0001f9e0', 'noon': '\U0001f55c', 'sick': '\U0001f912',
    'metro': '\U0001f687', 'station': '\U0001f689', 'palace': '\U0001f3f0',
    'tower': '\U0001f5fc', 'might': '\U0001f4aa', 'passport': '\U0001f4d5',
    'countryside': '\U0001f33e', 'surprised': '\U0001f632', 'deer': '\U0001f98c',
    'probably': '\U0001f914', 'pack': '\U0001f392', 'bathroom': '\U0001f6bf',
    'bedroom': '\U0001f6cf\ufe0f', 'balcony': '\U0001f33f', 'invite': '\U0001f48c',
    'arrival': '\U0001f6e2\ufe0f', 'add': '\u2795', 'biscuit': '\U0001f36a',
    'borrow': '\U0001f4da', 'plan': '\U0001f4cb', 'treasure': '\U0001f48e',
    'hunt': '\U0001f50d', 'lift': '\U0001f6d7', 'until': '\u23f3',
    'movie': '\U0001f3ac', 'dead': '\U0001f480', 'note': '\U0001f4dd',
    'community': '\U0001f3d8\ufe0f', 'rubbish': '\U0001f5d1\ufe0f', 'almost': '\U0001f51c',
    'journey': '\U0001f682', 'pull': '\U0001f579\ufe0f', 'luggage': '\U0001f9f3',
    'familiar': '\U0001f44b', 'joke': '\U0001f604', 'several': '3\ufe0f\u20e3',
    'nod': '\U0001f60a', 'writer': '\u270d\ufe0f', 'text': '\U0001f4d6',
    'describe': '\U0001f4ac', 'matter': '\u2753', 'perhaps': '\U0001f914',
    'plate': '\U0001f37d\ufe0f', 'smell': '\U0001f443', 'joy': '\U0001f389',
    'apartment': '\U0001f3e0', 'block': '\U0001f9f1', 'cover': '\U0001f4d5',
    'scissors': '\u2702\ufe0f', 'glue': '\U0001f9f4', 'compare': '\u2696\ufe0f',
    'shy': '\U0001f633', 'lazy': '\U0001f9a4', 'loud': '\U0001f4e2',
    'outgoing': '\U0001f604', 'perform': '\U0001f3ad', 'alone': '\U0001f464',
    'solve': '\U0001f9e9', 'flute': '\U0001f3b5', 'prize': '\U0001f3c5',
    'besides': '\u2795', 'spare': '\u23f0', 'pleasure': '\U0001f60a',
    'appearance': '\U0001f440', 'personality': '\U0001f9ec', 'serious': '\U0001f9d0',
    'strength': '\U0001f4aa', 'slim': '\U0001f9d8', 'fact': '\U0001f4cb',
    'population': '\U0001f465', 'average': '\U0001f4ca', 'rainfall': '\U0001f327\ufe0f',
    'pleasant': '\U0001f60a', 'difference': '\U0001f500', 'alike': '\U0001f46f',
    'mirror': '\U0001fa9e', 'interest': '\U0001f3af', 'novel': '\U0001f4d6',
    'sense': '\U0001f443', 'humour': '\U0001f604', 'opinion': '\U0001f4ad',
    'honest': '\U0001f9d0', 'direct': '\u27a1\ufe0f', 'friendship': '\U0001f91d',
    'metre': '\U0001f4cf', 'prince': '\U0001f9d3', 'character': '\U0001f464',
    'exchange': '\U0001f504', 'accident': '\U0001f4a5', 'expect': '\U0001f52e',
    'silver': '\U0001f948', 'situation': '\U0001f4cd', 'touch': '\U0001f44b',
    'moss': '\U0001f33f', 'redwood': '\U0001f332', 'cheetah': '\U0001f406',
    'bamboo': '\U0001f38b', 'popular': '\U0001f525', 'goodness': '\U0001f496',
    'tool': '\U0001f527', 'actually': '\U0001f4a1', 'land': '\U0001f30d',
    'peony': '\U0001f338', 'lotus': '\U0001fab7', 'butterfly': '\U0001f98b',
    'wing': '\U0001faBD', 'frog': '\U0001f438', 'weigh': '\u2696\ufe0f',
    'ginkgo': '\U0001f33f', 'believe': '\U0001f4ad', 'province': '\U0001f5fa\ufe0f',
    'connect': '\U0001f517', 'imagine': '\U0001f4ad', 'honey': '\U0001f36f',
    'pollen': '\U0001f33c', 'action': '\U0001f3ac', 'planet': '\U0001fa90',
    'store': '\U0001f3ea', 'communicate': '\U0001f4ac', 'ecosystem': '\U0001f30d',
    'protect': '\U0001f6e1\ufe0f', 'importance': '\u2b50', 'title': '\U0001f3f7\ufe0f',
    'human': '\U0001f9d1', 'ant': '\U0001f41c', 'happiness': '\U0001f60a',
    'mushroom': '\U0001f344', 'ton': '\u2696\ufe0f', 'role': '\U0001f3ad',
    'pea': '\U0001f7e2', 'climate': '\U0001f321\ufe0f', 'ocean': '\U0001f30a',
    'tiny': '\U0001f50d', 'lively': '\U0001f389', 'pepper': '\U0001f336\ufe0f',
    'bake': '\U0001f35e', 'oven': '\U0001f525', 'flour': '\U0001f33e',
    'boil': '\u2668\ufe0f', 'butter': '\U0001f9c8', 'cheese': '\U0001f9c0',
    'mash': '\U0001f954', 'bowl': '\U0001f963', 'heat': '\U0001f525',
    'oil': '\U0001fad2', 'pan': '\U0001f373', 'simple': '\U0001f44c',
    'sour': '\U0001f34b', 'mess': '\U0001f5d1\ufe0f', 'pretty': '\U0001f33c',
    'Christmas': '\U0001f384', 'pancake': '\U0001f95e', 'dream': '\U0001f4ad',
    'university': '\U0001f393', 'memory': '\U0001f9e0', 'pumpkin': '\U0001f383',
    'pie': '\U0001f967', 'cinnamon': '\U0001f33f', 'sweetness': '\U0001f36c',
    'college': '\U0001f393', 'host': '\U0001f3a4', 'recipe': '\U0001f4d6',
    'cream': '\U0001f366', 'secret': '\U0001f92b', 'spaghetti': '\U0001f35d',
    'spoon': '\U0001f944', 'slice': '\U0001f52a', 'couple': '\U0001f491',
    'island': '\U0001f3dd\ufe0f', 'wife': '\U0001f469', 'separate': '\u2194\ufe0f',
    'born': '\U0001f476', 'yourself': '\U0001fa9e', 'engineer': '\u2699\ufe0f',
    'fashion': '\U0001f457', 'designer': '\U0001f3a8', 'director': '\U0001f3ac',
    'musician': '\U0001f3b5', 'essay': '\U0001f4dd', 'classic': '\U0001f4d6',
    'literature': '\U0001f4da', 'athlete': '\U0001f3c3', 'photographer': '\U0001f4f7',
    'painter': '\U0001f3a8', 'businessman': '\U0001f4bc', 'lawyer': '\u2696\ufe0f',
    'bath': '\U0001f6c1', 'able': '\U0001f4aa', 'stick': '\U0001f4cc',
    'physical': '\U0001f4aa', 'health': '\u2764\ufe0f', 'confident': '\U0001f60e',
    'wisely': '\U0001f9e0', 'paragraph': '\U0001f4c4', 'introduce': '\U0001f44b',
    'meaning': '\U0001f4a1', 'fail': '\u274c', 'ahead': '\u27a1\ufe0f',
    'design': '\U0001f3a8', 'bridge': '\U0001f309', 'form': '\U0001f4cb',
    'relationship': '\U0001f91d', 'energetic': '\u26a1', 'prediction': '\U0001f52e',
    'outer': '\U0001f680', 'ticket': '\U0001f3ab', 'positive': '\U0001f44d',
    'traffic': '\U0001f697', 'technology': '\U0001f4bb', 'transport': '\U0001f69a',
    'system': '\u2699\ufe0f', 'efficient': '\u26a1', 'education': '\U0001f4da',
    'partner': '\U0001f91d', 'winner': '\U0001f3c6', 'cure': '\U0001f48a',
    'cancer': '\U0001f397\ufe0f', 'concert': '\U0001f3b8', 'cash': '\U0001f4b0',
    'wallet': '\U0001f4b0', 'guest': '\U0001f464', 'researcher': '\U0001f52c',
    'research': '\U0001f52c', 'everywhere': '\U0001f30d', 'robotics': '\U0001f916',
    'industry': '\U0001f3ed', 'service': '\U0001f6e0\ufe0f', 'disaster': '\U0001f32a\ufe0f',
    'emergency': '\U0001f6a8', 'disappear': '\U0001f47b', 'pilot': '\U0001f468\u200d\u2688\ufe0f',
    'expert': '\U0001f393', 'creativity': '\U0001f4a1', 'intelligence': '\U0001f9e0',
    'mention': '\U0001f4ac', 'refrigerator': '\U0001f9ca', 'low': '\U0001f4c9',
    'accept': '\u2705', 'influence': '\U0001f30a', 'creative': '\U0001f3a8',
    'impossible': '\U0001f6ab', 'quality': '\u2b50', 'develop': '\U0001f4c8',
    'valuable': '\U0001f48e', 'medical': '\U0001f3e5', 'challenge': '\U0001f3d4\ufe0f',
    'task': '\U0001f4cb', 'depend': '\U0001f91d', 'communication': '\U0001f4ac',
    'sign': '\U0001f4dd', 'speaker': '\U0001f5e3\ufe0f', 'local': '\U0001f4cd',
    'professor': '\U0001f393', 'speech': '\U0001f3a4', 'argue': '\U0001f624',
    'calm': '\U0001f60c', 'worry': '\U0001f61f', 'chance': '\U0001f340',
    'difficulty': '\U0001f3d4\ufe0f', 'detail': '\U0001f50d', 'nervous': '\U0001f630',
    'stranger': '\U0001f464', 'carefully': '\U0001f440', 'continue': '\u25b6\ufe0f',
    'personal': '\U0001f464', 'sincere': '\U0001f496', 'offer': '\U0001f381',
    'trust': '\U0001f91d', 'event': '\U0001f4c5', 'cost': '\U0001f4b0',
    'benefit': '\u2705', 'reply': '\U0001f4ac', 'honour': '\U0001f3c5',
    'game': '\U0001f3ae', 'excited': '\U0001f389', 'sleep': '\U0001f634',
    'autumn': '\U0001f342', 'train': '\U0001f682', 'sweep': '\U0001f9f9',
    'floor': '\U0001f3e0', 'toilet': '\U0001f6bd', 'careful': '\u26a0\ufe0f',
    'face': '\U0001f60a', 'kitchen': '\U0001f373', 'word': '\U0001f4dd',
    'slow': '\U0001f422', 'earth': '\U0001f30d', 'meat': '\U0001f969',
    'grape': '\U0001f347', 'thin': '\U0001f4cf', 'worker': '\U0001f477',
    'fire': '\U0001f525', 'helpful': '\U0001f44d',
}
EMOJI.update(_raw_emoji)

# ============================================================
# 二、词根拆解（仅收录有把握的）
# ============================================================
WORD_ROOTS = {
    'unhappy': 'un-(不) + happy(开心)',
    'unable': 'un-(不) + able(能够)',
    'unknown': 'un-(不) + known(已知)',
    'unusual': 'un-(不) + usual(平常)',
    'unfair': 'un-(不) + fair(公平)',
    'unlucky': 'un-(不) + lucky(幸运)',
    'unfriendly': 'un-(不) + friendly(友好)',
    'uncomfortable': 'un-(不) + comfortable(舒适)',
    'impolite': 'im-(不) + polite(礼貌)',
    'impossible': 'im-(不) + possible(可能)',
    'incorrect': 'in-(不) + correct(正确)',
    'independent': 'in-(不) + dependent(依赖)',
    'irregular': 'ir-(不) + regular(规则)',
    'dishonest': 'dis-(不) + honest(诚实)',
    'disappear': 'dis-(否定) + appear(出现)',
    'disappoint': 'dis-(否定) + appoint -> 使失望',
    'disagree': 'dis-(否定) + agree(同意)',
    'disconnect': 'dis-(分开) + connect(连接)',
    'misunderstand': 'mis-(错误) + understand(理解)',
    'misuse': 'mis-(错误) + use(使用)',
    'return': 're-(回) + turn(转) -> 返回',
    'rewrite': 're-(再) + write(写) -> 重写',
    'reuse': 're-(再) + use(用) -> 重用',
    'recycle': 're-(再) + cycle(循环) -> 回收利用',
    'remind': 're-(再) + mind(心) -> 提醒',
    'replace': 're-(替换) + place(放置) -> 替换',
    'reply': 're-(回) + ply(折叠) -> 回复',
    'recover': 're-(回) + cover(覆盖) -> 恢复',
    'predict': 'pre-(预先) + dict(说) -> 预测',
    'preview': 'pre-(预先) + view(看) -> 预览',
    'prepare': 'pre-(预先) + pare(准备) -> 准备',
    'transport': 'trans-(跨越) + port(搬运) -> 运输',
    'translate': 'trans-(跨越) + late(搬运) -> 翻译',
    'transform': 'trans-(跨越) + form(形状) -> 转变',
    'internet': 'inter-(之间) + net(网) -> 互联网',
    'interview': 'inter-(之间) + view(看) -> 面试',
    'international': 'inter-(之间) + national(国家) -> 国际的',
    'discover': 'dis-(去掉) + cover(盖子) -> 发现',
    'discuss': 'dis-(分开) + cuss(敲击) -> 讨论',
    'overcome': 'over-(超越) + come(来) -> 克服',
    'overseas': 'over-(跨越) + seas(海) -> 海外',
    'understand': 'under-(在下面) + stand(站) -> 理解',
    'underground': 'under-(在下面) + ground(地) -> 地下',
    'outgoing': 'out-(向外) + going(走) -> 外向的',
    'outdoor': 'out-(向外) + door(门) -> 户外',
    'dictionary': 'dict(说) + -ion + -ary -> 词典',
    'important': 'im-(进入) + port(搬运) -> 重要的',
    'export': 'ex-(向外) + port(搬运) -> 出口',
    'import': 'im-(进入) + port(搬运) -> 进口',
    'report': 're-(回) + port(搬运) -> 报告',
    'support': 'sup-(在下) + port(搬运) -> 支持',
    'structure': 'struct(建造) + -ure -> 结构',
    'construct': 'con-(共同) + struct(建造) -> 建造',
    'project': 'pro-(向前) + ject(扔) -> 项目',
    'object': 'ob-(对面) + ject(扔) -> 物体',
    'inject': 'in-(进入) + ject(扔) -> 注射',
    'reject': 're-(回) + ject(扔) -> 拒绝',
    'visit': 'vis(看) + it -> 参观',
    'visible': 'vis(看) + -ible(能) -> 可见的',
    'video': 'vid(看) + -eo -> 视频',
    'vision': 'vis(看) + -ion -> 视力/愿景',
    'television': 'tele-(远) + vis(看) + -ion -> 电视',
    'produce': 'pro-(向前) + duc(引导) -> 生产',
    'introduce': 'intro-(向内) + duc(引导) -> 介绍',
    'education': 'e-(出) + duc(引导) + -ation -> 教育',
    'conduct': 'con-(共同) + duct(引导) -> 引导',
    'reduce': 're-(回) + duc(引导) -> 减少',
    'describe': 'de-(向下) + scrib(写) -> 描述',
    'subscribe': 'sub-(在下) + scrib(写) -> 订阅',
    'inspect': 'in-(进入) + spect(看) -> 检查',
    'respect': 're-(回) + spect(看) -> 尊重',
    'expect': 'ex-(向外) + spect(看) -> 期望',
    'commit': 'com-(共同) + mit(送) -> 承诺',
    'submit': 'sub-(在下) + mit(送) -> 提交',
    'permit': 'per-(通过) + mit(送) -> 允许',
    'promise': 'pro-(向前) + mis(送) -> 承诺',
    'admit': 'ad-(朝向) + mit(送) -> 承认',
    'dismiss': 'dis-(分开) + mis(送) -> 解散',
    'accept': 'ac-(朝向) + cept(拿) -> 接受',
    'receive': 're-(回) + ceive(拿) -> 收到',
    'perceive': 'per-(完全) + ceive(拿) -> 感知',
    'attract': 'at-(朝向) + tract(拉) -> 吸引',
    'abstract': 'abs-(离开) + tract(拉) -> 抽象',
    'contract': 'con-(共同) + tract(拉) -> 合同',
    'distract': 'dis-(分开) + tract(拉) -> 分散',
    'inform': 'in-(进入) + form(形状) -> 通知',
    'perform': 'per-(完全) + form(形状) -> 表演',
    'reform': 're-(再) + form(形状) -> 改革',
    'uniform': 'uni-(一个) + form(形状) -> 制服',
    'convert': 'con-(完全) + vert(转) -> 转变',
    'advertise': 'ad-(朝向) + vert(转) + -ise -> 做广告',
    'interrupt': 'inter-(之间) + rupt(破) -> 打断',
    'erupt': 'e-(出) + rupt(破) -> 爆发',
    'vocabulary': 'voc(声音) + -abul + -ary -> 词汇表',
    'photograph': 'photo-(光) + graph(画) -> 照片',
    'paragraph': 'para-(旁边) + graph(写) -> 段落',
    'grammar': 'gram(写) + -mar -> 语法',
    'phone': 'phon(声音) + e -> 电话',
    'biology': 'bio(生命) + -logy(学科) -> 生物学',
    'biography': 'bio(生命) + -graphy(写) -> 传记',
    'geography': 'geo(地球) + -graphy(写) -> 地理学',
    'technology': 'techno(技术) + -logy(学科) -> 技术',
    'ecology': 'eco(生态) + -logy(学科) -> 生态学',
    'popular': 'popul(人民) + -ar -> 受欢迎的',
    'family': '拉丁语 familia(家庭)',
    'happy': '古英语 hap(运气) + -y -> 有运气的',
    'beautiful': 'beauty(美) + -ful(充满) -> 充满美的',
    'wonderful': 'wonder(奇迹) + -ful(充满) -> 充满奇迹的',
    'different': 'dif-(分开) + fer(带来) -> 不同的',
    'dangerous': 'danger(危险) + -ous -> 危险的',
    'ancient': '源自拉丁语 antiquus(古老的)',
    'vacation': 'vacat(空闲) + -ion -> 假期',
    'information': 'in-(进入) + form(形状) + -ation -> 信息',
    'communication': 'com-(共同) + muni(交流) + -cation -> 交流',
    'environment': 'environ(周围) + -ment -> 环境',
    'development': 'de-(向下) + velop(包裹) + -ment -> 发展',
    'experience': 'ex-(出) + peri(尝试) + -ence -> 经验',
    'experiment': 'ex-(出) + peri(尝试) + -ment -> 实验',
    'population': 'popul(人民) + -ation -> 人口',
    'relationship': 'relation(关系) + -ship -> 关系',
    'competition': 'com-(共同) + pet(追求) + -ition -> 竞争',
    'conversation': 'con-(共同) + vers(转) + -ation -> 对话',
    'situation': 'situa(位置) + -tion -> 情况',
    'national': 'nation(国家) + -al -> 国家的',
    'personal': 'person(人) + -al -> 个人的',
    'creative': 'creat(创造) + -ive -> 有创造力的',
    'active': 'act(行动) + -ive -> 活跃的',
    'nervous': 'nerv(神经) + -ous -> 紧张的',
    'curious': 'cur(关心) + -ious -> 好奇的',
    'famous': 'fam(名声) + -ous -> 著名的',
    'confident': 'con-(完全) + fid(信任) -> 自信的',
    'responsible': 're-(回) + spons(承诺) -> 负责的',
    'possible': 'poss(能够) + -ible -> 可能的',
    'comfortable': 'com-(共同) + fort(力量) + -able -> 舒适的',
    'reasonable': 'reason(理由) + -able -> 合理的',
    'valuable': 'valu(价值) + -able -> 有价值的',
    'friendship': 'friend(朋友) + -ship -> 友谊',
    'leadership': 'leader(领导者) + -ship -> 领导力',
    'championship': 'champion(冠军) + -ship -> 锦标赛',
    'scientist': 'scient(知识) + -ist -> 科学家',
    'artist': 'art(艺术) + -ist -> 艺术家',
    'tourist': 'tour(旅行) + -ist -> 游客',
    'journalist': 'journal(日报) + -ist -> 记者',
    'education': 'e-(出) + duc(引导) + -ation -> 教育',
    'instruction': 'in-(进入) + struct(建造) + -tion -> 指导',
    'prediction': 'pre-(预先) + dict(说) + -ion -> 预测',
    'attention': 'at-(朝向) + tent(伸展) + -ion -> 注意力',
    'suggestion': 'sug-(在下) + gest(带来) + -ion -> 建议',
    'expression': 'ex-(出) + press(压) + -ion -> 表达',
    'impression': 'im-(进入) + press(压) + -ion -> 印象',
    'decision': 'de-(完全) + cis(切) + -ion -> 决定',
    'discussion': 'dis-(分开) + cuss(敲击) + -ion -> 讨论',
    'collection': 'col-(共同) + lect(选择) + -ion -> 收藏',
    'protection': 'pro-(向前) + tect(覆盖) + -ion -> 保护',
    'connection': 'con-(共同) + nect(连接) + -ion -> 连接',
    'action': 'act(行动) + -ion -> 行动',
    'introduction': 'intro-(向内) + duc(引导) + -tion -> 介绍',
    'adventure': 'ad-(朝向) + vent(来) -> 冒险',
    'nature': 'nat(出生) + -ure -> 自然',
    'culture': 'cult(培养) + -ure -> 文化',
    'future': 'fut(将要) + -ure -> 未来',
    'literature': 'liter(文字) + -ature -> 文学',
    'treasure': 'treas(宝库) + -ure -> 宝藏',
    'pressure': 'press(压) + -ure -> 压力',
    'pleasure': 'pleas(愉悦) + -ure -> 愉快',
    'failure': 'fail(失败) + -ure -> 失败',
    'courage': 'cour(心) + -age -> 勇气',
    'package': 'pack(打包) + -age -> 包裹',
    'message': 'mess(送) + -age -> 信息',
    'language': 'langu(舌头) + -age -> 语言',
    'encourage': 'en-(使) + cour(心) + -age -> 鼓励',
    'passage': 'pass(通过) + -age -> 通道',
    'average': '源自阿拉伯语 awar(损坏的货物) -> 平均',
    'pollution': 'pollut(污染) + -ion -> 污染',
    'solution': 'solu(松开) + -tion -> 解决方案',
    'production': 'pro-(向前) + duct(引导) + -tion -> 生产',
    'description': 'de-(向下) + scrib(写) + -tion -> 描述',
    'creation': 'crea(创造) + -tion -> 创造',
    'pronunciation': 'pro-(向前) + nunci(说) + -ation -> 发音',
    'operation': 'oper(工作) + -ation -> 操作',
    'temperature': 'temper(混合) + -ature -> 温度',
    'picture': 'pict(画) + -ure -> 图片',
    'furniture': 'furn(提供) + -iture -> 家具',
    'departure': 'de-(离开) + part(部分) -> 出发',
    'storage': 'stor(存放) + -age -> 存储',
    'voyage': 'voy(路) + -age -> 航行',
}

# ============================================================
# 三、联想记忆（谐音 / 拆分 / 首字母）
# ============================================================
MNEMONICS = {
    'ancient': 'ancient 谐音 安神的，古代庙宇让人安神',
    'vacation': 'vacation 谐音 我开心，假期我开心',
    'fantastic': 'fan(粉丝) + tastic，粉丝都觉得太棒了',
    'landscape': 'land(土地) + scape(景色) -> 一片土地的景色',
    'breath': 'bre 谐音 不累，呼吸不能停',
    'especially': 'especial(特别的) + -ly -> 尤其',
    'anywhere': 'any(任何) + where(哪里) -> 任何地方',
    'nothing': 'no(没有) + thing(东西) -> 什么都没有',
    'guide': 'guide 谐音 归的，导游归你管',
    'scenery': 'scen 谐音 山顶，山顶风景好',
    'silk': 'silk 谐音 丝绸',
    'scarf': 'scarf 谐音 死卡夫，围巾卡在脖子上',
    'ready': 'read(读) + y -> 读完 = 准备好了',
    'hotel': 'hotel 谐音 好特，好特别的酒店',
    'comfortable': 'com-(共同) + fort(力量) -> 共同有力量 = 舒适',
    'sky': 'sky 谐音 死盖，天空像盖子',
    'rainbow': 'rain(雨) + bow(弓) -> 雨后的弓 = 彩虹',
    'victory': 'victory 谐音 维克多，胜利属于维克多',
    'peace': 'peace 谐音 皮思，和平年代皮思',
    'forget': 'for(为了) + get(得到) -> 为了新忘旧',
    'sick': 'sick 谐音 死渴，生病了死渴',
    'metro': 'metro 谐音 迈德罗',
    'palace': 'pal(朋友) + ace -> 朋友住宫殿',
    'tower': 'tower 谐音 头儿，塔的头儿最高',
    'passport': 'pass(通过) + port(港口) -> 通过港口的证件',
    'probably': 'probable(可能的) + -ly -> 可能地',
    'pack': 'pack 谐音 拍客，打包行李的拍客',
    'bathroom': 'bath(洗澡) + room(房间) -> 浴室',
    'bedroom': 'bed(床) + room(房间) -> 卧室',
    'balcony': 'balcony 谐音 白看你，阳台白看风景',
    'invite': 'in-(进入) + vite(邀请) -> 邀请进入',
    'add': 'add 谐音 爱的，加上爱的',
    'biscuit': 'bis(二) + cuite(快) -> 两口快吃完的饼干',
    'treasure': 'treasure 谐音 踹热，踹开热土找宝藏',
    'hunt': 'hunt 谐音 憨特，憨憨地特别爱打猎',
    'until': 'un-(不) + til(倾斜) -> 不倾斜 = 直到',
    'movie': 'movie 谐音 木维，电影里的木头维纳斯',
    'community': 'com-(共同) + muni(交流) -> 共同交流 = 社区',
    'rubbish': 'rub(擦) + bish -> 擦掉的垃圾',
    'almost': 'al-(全) + most(最多) -> 几乎全部',
    'journey': 'journey 谐音 截你，旅程截住你',
    'pull': 'pull 谐音 扑了，扑过去拉',
    'luggage': 'lugg(拉) + age -> 拉着的东西 = 行李',
    'familiar': 'fa-(做) + mili(家庭) -> 像家人一样熟悉',
    'writer': 'write(写) + -er -> 写字的人',
    'describe': 'de-(向下) + scrib(写) -> 写下来 = 描述',
    'matter': 'matter 谐音 麦特，麦特的事 = 问题',
    'perhaps': 'per-(通过) + hap(运气) -> 通过运气 = 也许',
    'smell': 'smell 谐音 死卖哦，死卖哦好臭',
    'joy': 'joy 谐音 解忧，快乐解忧',
    'apartment': 'apart(分开) + -ment -> 分开的房间 = 公寓',
    'scissors': 'sci(知道) + ssors -> 知道怎么剪 = 剪刀',
    'compare': 'com-(共同) + pare(比较) -> 共同比较',
    'lazy': 'lazy 谐音 累贼，懒人累成贼',
    'outgoing': 'out-(向外) + going(走) -> 向外走 = 外向',
    'perform': 'per-(完全) + form(形状) -> 完全展现 = 表演',
    'solve': 'solve 谐音 扫五，扫五题解决',
    'flute': 'flute 谐音 拂绿，笛声拂过绿林',
    'prize': 'prize 谐音 普来兹，普来兹获奖',
    'attend': 'at-(朝向) + tend(伸展) -> 朝向伸展 = 参加',
    'besides': 'be-(在) + side(旁边) -> 在旁边 = 除了',
    'pleasure': 'pleas(愉悦) + -ure -> 愉快',
    'appearance': 'appear(出现) + -ance -> 外表',
    'personality': 'person(人) + -ality -> 个性',
    'strength': 'strong(强) -> 力量',
    'population': 'popul(人民) + -ation -> 人口',
    'pleasant': 'pleas(愉悦) + -ant -> 令人愉快的',
    'difference': 'dif-(分开) + fer(带来) -> 差别',
    'interest': 'inter-(在中间) + est -> 在中间停住 = 兴趣',
    'novel': 'novel 谐音 闹欧，新小说闹欧洲',
    'opinion': 'opinion 谐音 哦拼你，哦拼你的意见',
    'honest': 'honest 谐音 奥尼斯，诚实的奥尼斯',
    'direct': 'di-(完全) + rect(直) -> 完全直的 = 直接',
    'friendship': 'friend(朋友) + -ship -> 友谊',
    'prince': 'prince 谐音 普林斯，普林斯王子',
    'exchange': 'ex-(出) + change(变化) -> 交换',
    'accident': 'ac-(朝向) + cid(落下) -> 朝向落下 = 意外',
    'expect': 'ex-(向外) + spect(看) -> 向外看 = 期望',
    'touch': 'touch 踏去，踏去触摸',
    'moss': 'moss 谐音 冒丝，苔藓冒出丝丝',
    'bamboo': 'bamboo 谐音 班布，班布是竹子',
    'popular': 'popul(人民) + -ar -> 受欢迎的',
    'tool': 'tool 谐音 兔哦，工具像兔子',
    'land': 'land 谐音 蓝的，蓝色的土地',
    'butterfly': 'butter(黄油) + fly(飞) -> 黄油飞 = 蝴蝶',
    'believe': 'be-(在) + lieve(相信) -> 相信',
    'province': 'province 谐音 破文思，省份破文思',
    'connect': 'con-(共同) + nect(连接) -> 共同连接',
    'imagine': 'im-(进入) + agine(想象) -> 进入想象',
    'honey': 'honey 谐音 哈尼，亲爱的哈尼',
    'planet': 'planet 谐音 普兰特，行星普兰特',
    'store': 'store 谐音 死多，商店死多东西',
    'communicate': 'com-(共同) + muni(交流) + -cate -> 共同交流',
    'protect': 'pro-(向前) + tect(覆盖) -> 在前面覆盖 = 保护',
    'importance': 'import(重要) + -ance -> 重要性',
    'ant': 'ant 谐音 俺特，俺特爱蚂蚁',
    'happiness': 'happy(开心) + -ness -> 幸福',
    'mushroom': 'mush(糊) + room -> 糊状的房间 = 蘑菇',
    'climate': 'clim(爬) + ate -> 爬过不同气候',
    'ocean': 'ocean 谐音 哦深，海洋哦深',
    'pepper': 'pepper 谐音 拍拍，辣椒拍拍嘴',
    'bake': 'bake 谐音 贝克，贝克烤面包',
    'simple': 'simple 谐音 森剖，简单地剖开',
    'sour': 'sour 谐音 扫二，酸得扫二遍',
    'Christmas': 'Christ(基督) + mas(弥撒) -> 圣诞节',
    'dream': 'dream 谐音 追梦，做梦追梦',
    'university': 'uni-(一个) + vers(转) -> 一个转的地方 = 大学',
    'memory': 'memory 谐音 卖莫里，卖莫里的记忆',
    'pumpkin': 'pump(泵) + kin -> 泵出来的大家伙 = 南瓜',
    'college': 'col-(共同) + lege(法律) -> 共同学法律的地方',
    'host': 'host 谐音 厚实的，主人厚实的',
    'recipe': 'recipe 谐音 瑞思碧，瑞思碧的食谱',
    'secret': 'secret 谐音 思克瑞特，思克瑞特的秘密',
    'island': 'is(是) + land(地) -> 是陆地 = 岛',
    'born': 'born 谐音 波恩，波恩出生',
    'engineer': 'engine(引擎) + er -> 引擎的人 = 工程师',
    'fashion': 'fashion 谐音 费兴，时尚费兴',
    'photographer': 'photo(光) + graph(画) + -er -> 摄影师',
    'literature': 'liter(文字) + -ature -> 文学',
    'athlete': 'athlete 谐音 爱实力，运动员爱实力',
    'businessman': 'business(生意) + man -> 商人',
    'lawyer': 'law(法律) + -yer -> 律师',
    'resolution': 're-(再) + solu(松开) + -tion -> 决心',
    'physical': 'physic(医学) + -al -> 身体的',
    'confident': 'con-(完全) + fid(信任) -> 自信',
    'paragraph': 'para-(旁边) + graph(写) -> 段落',
    'introduce': 'intro-(向内) + duc(引导) -> 介绍',
    'meaning': 'mean(意思) + -ing -> 意义',
    'fail': 'fail 谐音 飞偶，飞偶失败了',
    'ahead': 'a-(朝向) + head(头) -> 朝向头 = 向前',
    'design': 'de-(向下) + sign(标记) -> 标记出来 = 设计',
    'relationship': 'relation(关系) + -ship -> 关系',
    'energetic': 'energy(精力) + -tic -> 精力充沛的',
    'prediction': 'pre-(预先) + dict(说) + -ion -> 预测',
    'positive': 'posi(位置) + tive -> 找到正确位置 = 积极',
    'technology': 'techno(技术) + -logy(学科) -> 技术',
    'transport': 'trans-(跨越) + port(搬运) -> 运输',
    'efficient': 'ef-(出) + fic(做) -> 做出来有效率',
    'education': 'e-(出) + duc(引导) + -ation -> 教育',
    'partner': 'partner 谐音 帕特纳，帕特纳伙伴',
    'winner': 'win(赢) + -ner -> 赢家',
    'cure': 'cure 谐音 哭儿，哭儿需要治愈',
    'concert': 'con-(共同) + cert(确定) -> 共同确定 = 音乐会',
    'research': 're-(再) + search(搜索) -> 再搜索 = 研究',
    'industry': 'indu(引导) + stry -> 引导产业',
    'disaster': 'dis-(否定) + aster(星) -> 坏星 = 灾难',
    'emergency': 'emerge(出现) + -ncy -> 紧急情况',
    'disappear': 'dis-(否定) + appear(出现) -> 消失',
    'pilot': 'pilot 谐音 派乐的，派乐的飞行员',
    'expert': 'ex-(出) + pert(尝试) -> 尝试很多次 = 专家',
    'creativity': 'creat(创造) + -ivity -> 创造力',
    'intelligence': 'in-(之间) + tellig(选择) -> 智力',
    'refrigerator': 're-(再) + friger(冷) -> 再次冷却 = 冰箱',
    'influence': 'in-(进入) + flu(流) -> 流进去 = 影响',
    'creative': 'creat(创造) + -ive -> 创造性的',
    'develop': 'de-(向下) + velop(包裹) -> 展开 = 发展',
    'challenge': 'challenge 谐音 才令准，挑战才令准',
    'depend': 'de-(向下) + pend(挂) -> 挂在下面 = 依赖',
    'communication': 'com-(共同) + muni(交流) + -cation -> 交流',
    'professor': 'pro-(向前) + fess(说) + -or -> 教授',
    'speech': 'speak(说) -> 演讲',
    'argue': 'argue 谐音 啊古，啊古在争论',
    'calm': 'calm 谐音 卡木，卡木很冷静',
    'nervous': 'nerv(神经) + -ous -> 紧张的',
    'stranger': 'strange(陌生的) + -r -> 陌生人',
    'continue': 'con-(共同) + tin(保持) -> 共同保持 = 继续',
    'personal': 'person(人) + -al -> 个人的',
    'sincere': 'sincere 谐音 辛思尔，辛思尔真诚的',
    'offer': 'offer 谐音 奥佛，奥佛提供',
    'trust': 'trust 谐音 踹死特，信任踹死特',
    'event': 'e-(出) + vent(来) -> 出来的事 = 事件',
    'benefit': 'bene-(好) + fit(做) -> 做好事 = 好处',
    'reply': 're-(回) + ply(折叠) -> 折回去 = 回复',
    'honour': 'honour 谐音 哈呢，哈呢荣誉',
    'excited': 'ex-(出) + cit(叫) -> 叫出来 = 兴奋',
    'autumn': 'autumn 谐音 奥特姆，奥特姆秋天',
    'train': 'train 谐音 踹恩，踹恩火车',
    'sweep': 'sweep 谐音 思威普，思威普扫地',
    'careful': 'care(关心) + -ful -> 小心的',
    'face': 'face 谐音 费斯，费斯脸',
    'kitchen': 'kitchen 谐音 起珍，起珍厨房',
    'slow': 'slow 谐音 丝漏，丝漏慢吞吞',
    'earth': 'earth 谐音 饿死，地球饿死了',
    'meat': 'meat 谐音 米特，米特肉',
    'worker': 'work(工作) + -er -> 工人',
    'fire': 'fire 谐音 发哦，发哦火',
    'helpful': 'help(帮助) + -ful -> 有帮助的',
    'quality': 'quality 谐音 夸利体，夸利体质量',
    'valuable': 'valu(价值) + -able -> 有价值的',
    'honest': '源自拉丁语 honestus(尊敬的)',
    'friend': '古英语 freond(爱、偏好)，朋友',
    'excited': 'ex-(出) + cit(叫) -> 叫出来 = 兴奋',
}

# ============================================================
# 四、例句生成（最简句型）
# ============================================================
def gen_example(word, pos, meaning):
    w = word.split()[0].lower()
    pl = pos.lower() if pos else ''

    # 特殊短语/词组
    if ' ' in word:
        return 'I can use this phrase in a sentence.'

    # 动词
    if 'v.' in pl:
        verb_forms = {
            'like': 'I like English very much.',
            'love': 'I love my family.',
            'enjoy': 'I enjoy reading books.',
            'need': 'I need your help.',
            'want': 'I want to be a teacher.',
            'can': 'Yes, I can.',
            'have': 'I have a new book.',
            'has': 'She has a cute cat.',
            'do': 'I do my homework every day.',
            'go': 'I go to school every day.',
            'come': 'Come here, please.',
            'take': 'I take a walk every day.',
            'make': 'I make a cake.',
            'give': 'I give you a gift.',
            'get': 'I get up at 7:00.',
            'see': 'I see a bird in the tree.',
            'know': 'I know the answer.',
            'think': 'I think so.',
            'say': 'I say hello to you.',
            'tell': 'I tell you a story.',
            'eat': 'I eat breakfast at 7:00.',
            'drink': 'I drink water every day.',
            'run': 'I run every morning.',
            'swim': 'I like to swim.',
            'sing': 'I like to sing.',
            'dance': 'I like to dance.',
            'read': 'I read books every day.',
            'write': 'I write a letter.',
            'draw': 'I like to draw.',
            'play': 'I like to play football.',
            'study': 'I study English every day.',
            'learn': 'I learn new words.',
            'teach': 'She teaches English.',
            'work': 'He works very hard.',
            'open': 'Please open the door.',
            'close': 'Please close the door.',
            'start': 'Let us start now.',
            'finish': 'I finish my homework.',
            'try': 'I try my best.',
            'help': 'I help my mother.',
            'ask': 'I ask a question.',
            'answer': 'I answer the question.',
            'wait': 'I wait for you.',
            'stop': 'Please stop here.',
            'move': 'Please move on.',
            'turn': 'Please turn left.',
            'bring': 'Please bring your book.',
            'build': 'We build a house.',
            'cut': 'I cut the paper.',
            'put': 'Please put it here.',
            'keep': 'I keep a diary.',
            'let': 'Please let me go.',
            'show': 'Please show me your book.',
            'check': 'I check my homework.',
            'choose': 'I choose the red one.',
            'decide': 'I decide to go.',
            'describe': 'Please describe the picture.',
            'explain': 'Please explain it to me.',
            'introduce': 'Let me introduce myself.',
            'offer': 'He offers to help.',
            'reply': 'Please reply to me.',
            'suggest': 'I suggest a new idea.',
            'believe': 'I believe you.',
            'expect': 'I expect to see you.',
            'hope': 'I hope so.',
            'wish': 'I wish you good luck.',
            'dream': 'I dream of flying.',
            'feel': 'I feel happy.',
            'look': 'Please look at me.',
            'listen': 'I listen to music.',
            'watch': 'I watch TV every day.',
            'call': 'I call my friend.',
            'meet': 'I meet you at school.',
            'join': 'I want to join you.',
            'leave': 'I leave home at 7:00.',
            'stay': 'I stay at home.',
            'return': 'I return home at 5:00.',
            'visit': 'I visit my grandparents.',
            'travel': 'I like to travel.',
            'arrive': 'I arrive at school at 8:00.',
            'happen': 'What happens next?',
            'succeed': 'I hope to succeed.',
            'fail': 'I do not want to fail.',
            'win': 'I want to win.',
            'fight': 'I do not like to fight.',
            'argue': 'I do not like to argue.',
            'worry': 'Do not worry.',
            'solve': 'I can solve this problem.',
            'perform': 'I like to perform on stage.',
            'compare': 'I compare the two books.',
            'connect': 'Please connect to the Internet.',
            'communicate': 'I communicate with my friends.',
            'depend': 'It depends on the weather.',
            'accept': 'I accept your invitation.',
            'reply': 'I reply to the email.',
            'mention': 'He mentions it to me.',
            'design': 'I design a new poster.',
            'introduce': 'Let me introduce myself.',
            'predict': 'I predict it will be sunny.',
            'continue': 'Please continue your work.',
            'trust': 'I trust you.',
            'offer': 'She offers to help.',
            'suggest': 'I suggest we go now.',
            'imagine': 'I imagine a beautiful world.',
            'believe': 'I believe in you.',
        }
        if w in verb_forms:
            return verb_forms[w]
        return f'I {w} every day.'

    # 形容词
    if 'adj.' in pl:
        adj_forms = {
            'good': 'This is very good.',
            'bad': 'This is very bad.',
            'big': 'The box is very big.',
            'small': 'The box is very small.',
            'hot': 'The weather is hot.',
            'cold': 'The weather is cold.',
            'warm': 'The weather is warm.',
            'new': 'This is a new book.',
            'old': 'This is an old book.',
            'long': 'The road is very long.',
            'short': 'The road is very short.',
            'fast': 'The car is very fast.',
            'slow': 'The car is very slow.',
            'happy': 'I am very happy.',
            'sad': 'I am very sad.',
            'easy': 'This is very easy.',
            'hard': 'This is very hard.',
            'important': 'This is very important.',
            'useful': 'This is very useful.',
            'beautiful': 'The flower is beautiful.',
            'quiet': 'The room is very quiet.',
            'dangerous': 'This place is dangerous.',
            'safe': 'This place is safe.',
            'famous': 'He is very famous.',
            'serious': 'He is very serious.',
            'honest': 'He is an honest boy.',
            'clever': 'She is very clever.',
            'kind': 'She is very kind.',
            'brave': 'He is very brave.',
            'ancient': 'This is an ancient city.',
            'strange': 'This is very strange.',
            'comfortable': 'This chair is comfortable.',
            'fantastic': 'This is fantastic.',
            'popular': 'This song is very popular.',
            'creative': 'She is very creative.',
            'confident': 'I am very confident.',
            'energetic': 'He is very energetic.',
            'nervous': 'I am very nervous.',
            'surprised': 'I am very surprised.',
            'disappointed': 'I am very disappointed.',
            'excited': 'I am very excited.',
            'pleased': 'I am very pleased.',
            'worried': 'I am very worried.',
            'interested': 'I am very interested.',
            'bored': 'I am very bored.',
            'tired': 'I am very tired.',
            'sick': 'I am very sick.',
            'ill': 'I am very ill.',
            'weak': 'I am very weak.',
            'strong': 'He is very strong.',
            'slim': 'She is very slim.',
            'thin': 'He is very thin.',
            'fat': 'The cat is very fat.',
            'heavy': 'The bag is very heavy.',
            'light': 'The bag is very light.',
            'dark': 'The room is very dark.',
            'bright': 'The room is very bright.',
            'clean': 'The room is very clean.',
            'dirty': 'The room is very dirty.',
            'dry': 'The weather is very dry.',
            'wet': 'The weather is very wet.',
            'soft': 'The pillow is very soft.',
            'hard': 'The rock is very hard.',
            'sweet': 'The candy is very sweet.',
            'sour': 'The lemon is very sour.',
            'bitter': 'The medicine is very bitter.',
            'delicious': 'The food is delicious.',
            'lovely': 'The baby is very lovely.',
            'ugly': 'The monster is very ugly.',
            'tiny': 'The ant is very tiny.',
            'huge': 'The elephant is huge.',
            'deep': 'The river is very deep.',
            'shallow': 'The river is very shallow.',
            'wide': 'The road is very wide.',
            'narrow': 'The road is very narrow.',
            'flat': 'The land is very flat.',
            'rough': 'The road is very rough.',
            'smooth': 'The road is very smooth.',
            'simple': 'This is very simple.',
            'complex': 'This is very complex.',
            'correct': 'Your answer is correct.',
            'wrong': 'Your answer is wrong.',
            'real': 'This is a real story.',
            'true': 'This is a true story.',
            'false': 'This is a false answer.',
            'same': 'We have the same book.',
            'different': 'We have different ideas.',
            'similar': 'We have similar interests.',
            'alike': 'We look very alike.',
            'ordinary': 'This is very ordinary.',
            'special': 'This is very special.',
            'common': 'This is very common.',
            'rare': 'This is very rare.',
            'valuable': 'This is very valuable.',
            'worthless': 'This is very worthless.',
            'pleasant': 'The weather is pleasant.',
            'unpleasant': 'The weather is unpleasant.',
            'quiet': 'The room is very quiet.',
            'noisy': 'The room is very noisy.',
            'loud': 'The music is very loud.',
            'silent': 'The room is very silent.',
            'active': 'He is very active.',
            'lazy': 'He is very lazy.',
            'busy': 'I am very busy.',
            'free': 'I am very free.',
            'available': 'This is available.',
            'possible': 'This is possible.',
            'impossible': 'This is impossible.',
            'necessary': 'This is necessary.',
            'unnecessary': 'This is unnecessary.',
            'important': 'This is very important.',
            'unimportant': 'This is very unimportant.',
            'main': 'This is the main reason.',
            'key': 'This is the key point.',
            'vital': 'This is very vital.',
            'basic': 'This is very basic.',
            'fundamental': 'This is very fundamental.',
            'general': 'This is a general idea.',
            'specific': 'This is a specific example.',
            'particular': 'This is a particular case.',
            'clear': 'The answer is very clear.',
            'vague': 'The answer is very vague.',
            'direct': 'The answer is very direct.',
            'straightforward': 'The answer is very straightforward.',
            'reasonable': 'The answer is very reasonable.',
            'fair': 'The answer is very fair.',
            'unfair': 'The answer is very unfair.',
            'helpful': 'This is very helpful.',
            'useless': 'This is very useless.',
            'meaningful': 'This is very meaningful.',
            'meaningless': 'This is very meaningless.',
            'wonderful': 'This is very wonderful.',
            'terrible': 'This is very terrible.',
            'awful': 'This is very awful.',
            'amazing': 'This is very amazing.',
            'incredible': 'This is very incredible.',
            'unbelievable': 'This is very unbelievable.',
            'magnificent': 'This is very magnificent.',
            'splendid': 'This is very splendid.',
            'brilliant': 'This is very brilliant.',
            'excellent': 'This is very excellent.',
            'outstanding': 'This is very outstanding.',
            'superb': 'This is very superb.',
            'perfect': 'This is very perfect.',
            'complete': 'This is very complete.',
            'entire': 'This is very entire.',
            'whole': 'This is the whole story.',
            'full': 'The cup is very full.',
            'empty': 'The cup is very empty.',
            'hollow': 'The tree is very hollow.',
            'solid': 'The rock is very solid.',
            'liquid': 'Water is a liquid.',
            'frozen': 'The water is frozen.',
            'boiling': 'The water is boiling.',
            'melting': 'The ice is melting.',
            'rising': 'The sun is rising.',
            'falling': 'The leaves are falling.',
            'flying': 'The bird is flying.',
            'swimming': 'The fish is swimming.',
            'running': 'The dog is running.',
            'walking': 'The man is walking.',
            'sleeping': 'The baby is sleeping.',
            'waking': 'I am waking up.',
            'eating': 'I am eating dinner.',
            'drinking': 'I am drinking water.',
            'reading': 'I am reading a book.',
            'writing': 'I am writing a letter.',
            'studying': 'I am studying English.',
            'teaching': 'I am teaching students.',
            'learning': 'I am learning Chinese.',
            'playing': 'I am playing games.',
            'singing': 'I am singing a song.',
            'dancing': 'I am dancing happily.',
            'working': 'I am working hard.',
            'resting': 'I am resting now.',
            'waiting': 'I am waiting for you.',
            'thinking': 'I am thinking about it.',
            'wondering': 'I am wondering why.',
            'hoping': 'I am hoping for the best.',
            'wishing': 'I am wishing you well.',
            'dreaming': 'I am dreaming of success.',
            'believing': 'I am believing in you.',
            'trusting': 'I am trusting you.',
            'supporting': 'I am supporting you.',
            'helping': 'I am helping my friends.',
            'sharing': 'I am sharing my food.',
            'caring': 'I am caring for my pet.',
            'loving': 'I am loving my family.',
            'hating': 'I am hating the bad weather.',
            'liking': 'I am liking this song.',
            'enjoying': 'I am enjoying the show.',
            ' appreciating': 'I am appreciating the art.',
            'valuing': 'I am valuing your opinion.',
            'respecting': 'I am respecting my elders.',
            'admiring': 'I am admiring the view.',
            'praising': 'I am praising the winner.',
            'congratulating': 'I am congratulating the team.',
            'celebrating': 'I am celebrating the holiday.',
            'enjoying': 'I am enjoying the moment.',
            'cherishing': 'I am cherishing the memory.',
            'treasuring': 'I am treasuring the gift.',
            'keeping': 'I am keeping the secret.',
            'holding': 'I am holding the ball.',
            'carrying': 'I am carrying the box.',
            'lifting': 'I am lifting the weight.',
            'pulling': 'I am pulling the rope.',
            'pushing': 'I am pushing the door.',
            'opening': 'I am opening the window.',
            'closing': 'I am closing the door.',
            'turning': 'I am turning the page.',
            'moving': 'I am moving the chair.',
            'placing': 'I am placing the book.',
            'setting': 'I am setting the table.',
            'arranging': 'I am arranging the flowers.',
            'organizing': 'I am organizing the party.',
            'planning': 'I am planning the trip.',
            'preparing': 'I am preparing the meal.',
            'cooking': 'I am cooking dinner.',
            'baking': 'I am baking a cake.',
            'frying': 'I am frying an egg.',
            'boiling': 'I am boiling water.',
            'grilling': 'I am grilling meat.',
            'roasting': 'I am roasting chicken.',
            'steaming': 'I am steaming vegetables.',
            'mixing': 'I am mixing the ingredients.',
            'stirring': 'I am stirring the soup.',
            'tasting': 'I am tasting the food.',
            'smelling': 'I am smelling the flowers.',
            'touching': 'I am touching the cat.',
            'hearing': 'I am hearing the music.',
            'seeing': 'I am seeing the movie.',
            'watching': 'I am watching the game.',
            'listening': 'I am listening to the radio.',
            'observing': 'I am observing the stars.',
            'noticing': 'I am noticing the changes.',
            'recognizing': 'I am recognizing the face.',
            'remembering': 'I am remembering the past.',
            'forgetting': 'I am forgetting the bad things.',
            'learning': 'I am learning new skills.',
            'practicing': 'I am practicing the piano.',
            'improving': 'I am improving my English.',
            'developing': 'I am developing my talents.',
            'growing': 'I am growing taller.',
            'changing': 'I am changing for the better.',
            'becoming': 'I am becoming a better person.',
            'turning': 'I am turning eighteen.',
            'reaching': 'I am reaching my goal.',
            'achieving': 'I am achieving my dreams.',
            'accomplishing': 'I am accomplishing my mission.',
            'completing': 'I am completing my task.',
            'finishing': 'I am finishing my homework.',
            'ending': 'I am ending the day.',
            'starting': 'I am starting a new chapter.',
            'beginning': 'I am beginning my journey.',
            'launching': 'I am launching my career.',
            'opening': 'I am opening a new business.',
            'closing': 'I am closing the old chapter.',
            'leaving': 'I am leaving the old behind.',
            'entering': 'I am entering a new world.',
            'arriving': 'I am arriving at my destination.',
            'returning': 'I am returning home.',
            'departing': 'I am departing from the airport.',
            'traveling': 'I am traveling abroad.',
            'exploring': 'I am exploring the city.',
            'discovering': 'I am discovering new things.',
            'finding': 'I am finding my way.',
            'searching': 'I am searching for answers.',
            'looking': 'I am looking for my keys.',
            'seeking': 'I am seeking knowledge.',
            'asking': 'I am asking for help.',
            'answering': 'I am answering the phone.',
            'responding': 'I am responding to the email.',
            'reacting': 'I am reacting to the news.',
            'behaving': 'I am behaving well.',
            'acting': 'I am acting in the play.',
            'performing': 'I am performing on stage.',
            'showing': 'I am showing my work.',
            'displaying': 'I am displaying my art.',
            'exhibiting': 'I am exhibiting my photos.',
            'presenting': 'I am presenting my project.',
            'demonstrating': 'I am demonstrating the product.',
            'explaining': 'I am explaining the lesson.',
            'teaching': 'I am teaching English.',
            'instructing': 'I am instructing the class.',
            'guiding': 'I am guiding the tourists.',
            'leading': 'I am leading the team.',
            'directing': 'I am directing the movie.',
            'managing': 'I am managing the project.',
            'controlling': 'I am controlling the robot.',
            'operating': 'I am operating the machine.',
            'running': 'I am running the company.',
            'handling': 'I am handling the situation.',
            'dealing': 'I am dealing with the problem.',
            'solving': 'I am solving the puzzle.',
            'fixing': 'I am fixing the computer.',
            'repairing': 'I am repairing the car.',
            'building': 'I am building a house.',
            'constructing': 'I am constructing a bridge.',
            'making': 'I am making a plan.',
            'creating': 'I am creating a new design.',
            'producing': 'I am producing a movie.',
            'developing': 'I am developing a new app.',
            'inventing': 'I am inventing a new device.',
            'designing': 'I am designing a poster.',
            'planning': 'I am planning a party.',
            'organizing': 'I am organizing an event.',
            'arranging': 'I am arranging a meeting.',
            'scheduling': 'I am scheduling an appointment.',
            'booking': 'I am booking a hotel.',
            'reserving': 'I am reserving a table.',
            'ordering': 'I am ordering a pizza.',
            'buying': 'I am buying a new phone.',
            'purchasing': 'I am purchasing a book.',
            'selling': 'I am selling my old bike.',
            'trading': 'I am trading my toys.',
            'exchanging': 'I am exchanging gifts.',
            'sharing': 'I am sharing my lunch.',
            'donating': 'I am donating to charity.',
            'giving': 'I am giving a present.',
            'offering': 'I am offering help.',
            'providing': 'I am providing information.',
            'supplying': 'I am supplying the goods.',
            'delivering': 'I am delivering the package.',
            'sending': 'I am sending a letter.',
            'mailing': 'I am mailing a postcard.',
            'posting': 'I am posting a message.',
            'publishing': 'I am publishing an article.',
            'broadcasting': 'I am broadcasting the news.',
            'reporting': 'I am reporting the story.',
            'announcing': 'I am announcing the results.',
            'declaring': 'I am declaring the winner.',
            'proclaiming': 'I am proclaiming the truth.',
            'stating': 'I am stating my opinion.',
            'expressing': 'I am expressing my feelings.',
            'communicating': 'I am communicating with friends.',
            'talking': 'I am talking to my teacher.',
            'speaking': 'I am speaking English.',
            'saying': 'I am saying goodbye.',
            'telling': 'I am telling a joke.',
            'narrating': 'I am narrating a story.',
            'describing': 'I am describing the scene.',
            'explaining': 'I am explaining the rule.',
            'clarifying': 'I am clarifying the meaning.',
            'interpreting': 'I am interpreting the poem.',
            'translating': 'I am translating the text.',
            'converting': 'I am converting the currency.',
            'transforming': 'I am transforming the room.',
            'altering': 'I am altering the dress.',
            'modifying': 'I am modifying the plan.',
            'adjusting': 'I am adjusting the volume.',
            'changing': 'I am changing my clothes.',
            'switching': 'I am switching channels.',
            'swapping': 'I am swapping seats.',
            'replacing': 'I am replacing the battery.',
            'substituting': 'I am substituting the ingredient.',
            'interchanging': 'I am interchanging the parts.',
            'alternating': 'I am alternating the colors.',
            'varying': 'I am varying the speed.',
            'diversifying': 'I am diversifying my portfolio.',
            'expanding': 'I am expanding my business.',
            'extending': 'I am extending the deadline.',
            'lengthening': 'I am lengthening the road.',
            'widening': 'I am widening the street.',
            'deepening': 'I am deepening the river.',
            'heightening': 'I am heightening the wall.',
            'increasing': 'I am increasing the price.',
            'raising': 'I am raising the flag.',
            'elevating': 'I am elevating the status.',
            'boosting': 'I am boosting the sales.',
            'enhancing': 'I am enhancing the quality.',
            'improving': 'I am improving the service.',
            'upgrading': 'I am upgrading the system.',
            'updating': 'I am updating the software.',
            'refreshing': 'I am refreshing the page.',
            'renewing': 'I am renewing the contract.',
            'restoring': 'I am restoring the painting.',
            'recovering': 'I am recovering from illness.',
            'healing': 'I am healing the wound.',
            'curing': 'I am curing the disease.',
            'treating': 'I am treating the patient.',
            'nursing': 'I am nursing the baby.',
            'caring': 'I am caring for the elderly.',
            'helping': 'I am helping the poor.',
            'assisting': 'I am assisting the disabled.',
            'supporting': 'I am supporting the team.',
            'encouraging': 'I am encouraging the students.',
            'motivating': 'I am motivating the workers.',
            'inspiring': 'I is inspiring the audience.',
            'uplifting': 'I am uplifting the spirit.',
            'comforting': 'I am comforting the child.',
            'soothing': 'I am soothing the pain.',
            'calming': 'I am calming the storm.',
            'relaxing': 'I am relaxing at home.',
            'resting': 'I am resting on the couch.',
            'sleeping': 'I am sleeping in the bed.',
            'dreaming': 'I am dreaming of vacation.',
            'waking': 'I am waking up early.',
            'rising': 'I am rising with the sun.',
            'setting': 'I am setting with the sun.',
            'shining': 'I am shining like a star.',
            'glowing': 'I am glowing with happiness.',
            'sparkling': 'I am sparkling with joy.',
            'twinkling': 'I am twinkling in the night.',
            'flashing': 'I am flashing a smile.',
            'beaming': 'I am beaming with pride.',
            'radiating': 'I am radiating warmth.',
            'emitting': 'I am emitting light.',
            'reflecting': 'I am reflecting on life.',
            'absorbing': 'I am absorbing knowledge.',
            'learning': 'I am learning new things.',
            'studying': 'I am studying for the exam.',
            'practicing': 'I am practicing the piano.',
            'training': 'I am training for the marathon.',
            'exercising': 'I am exercising daily.',
            'working': 'I am working out at the gym.',
            'jogging': 'I am jogging in the park.',
            'running': 'I am running a race.',
            'swimming': 'I am swimming in the lake.',
            'cycling': 'I am cycling to work.',
            'hiking': 'I am hiking in the mountains.',
            'climbing': 'I am climbing the hill.',
            'surfing': 'I am surfing the waves.',
            'skiing': 'I am skiing on the slopes.',
            'skating': 'I am skating on the ice.',
            'dancing': 'I am dancing at the party.',
            'singing': 'I am singing in the choir.',
            'playing': 'I am playing the guitar.',
            'performing': 'I am performing in the concert.',
            'acting': 'I am acting in the movie.',
            'directing': 'I am directing the play.',
            'producing': 'I am producing the show.',
            'composing': 'I am composing a song.',
            'writing': 'I am writing a poem.',
            'painting': 'I am painting a picture.',
            'drawing': 'I am drawing a portrait.',
            'sculpting': 'I am sculpting a statue.',
            'photographing': 'I am photographing the landscape.',
            'filming': 'I am filming the documentary.',
            'editing': 'I am editing the video.',
            'designing': 'I am designing the website.',
            'coding': 'I am coding the program.',
            'programming': 'I am programming the robot.',
            'engineering': 'I am engineering the bridge.',
            'architecting': 'I am architecting the building.',
            'planning': 'I am planning the city.',
            'managing': 'I am managing the team.',
            'directing': 'I am directing the company.',
            'leading': 'I am leading the project.',
            'guiding': 'I am guiding the students.',
            'teaching': 'I am teaching the class.',
            'mentoring': 'I am mentoring the interns.',
            'coaching': 'I am coaching the players.',
            'training': 'I am training the employees.',
            'supervising': 'I am supervising the workers.',
            'overseeing': 'I am overseeing the operation.',
            'monitoring': 'I am monitoring the system.',
            'evaluating': 'I am evaluating the results.',
            'assessing': 'I am assessing the situation.',
            'analyzing': 'I am analyzing the data.',
            'researching': 'I am researching the topic.',
            'investigating': 'I am investigating the case.',
            'examining': 'I am examining the evidence.',
            'inspecting': 'I am inspecting the building.',
            'checking': 'I am checking the answers.',
            'testing': 'I am testing the product.',
            'verifying': 'I am verifying the facts.',
            'confirming': 'I am confirming the reservation.',
            'approving': 'I am approving the request.',
            'accepting': 'I am accepting the offer.',
            'rejecting': 'I am rejecting the proposal.',
            'declining': 'I am declining the invitation.',
            'refusing': 'I am refusing the command.',
            'denying': 'I am denying the accusation.',
            'admitting': 'I am admitting my mistake.',
            'confessing': 'I am confessing my feelings.',
            'revealing': 'I am revealing the secret.',
            'hiding': 'I am hiding the truth.',
            'concealing': 'I am concealing the evidence.',
            'covering': 'I am covering the mistake.',
            'exposing': 'I am exposing the lie.',
            'uncovering': 'I am uncovering the mystery.',
            'discovering': 'I am discovering new things.',
            'exploring': 'I am exploring the cave.',
            'searching': 'I am searching for treasure.',
            'hunting': 'I am hunting for clues.',
            'seeking': 'I am seeking adventure.',
            'finding': 'I am finding my way home.',
            'losing': 'I am losing my keys.',
            'misplacing': 'I am misplacing my phone.',
            'forgetting': 'I am forgetting the address.',
            'remembering': 'I am remembering the lesson.',
            'recalling': 'I am recalling the memory.',
            'recollecting': 'I am recollecting the past.',
            'reflecting': 'I am reflecting on my life.',
            'contemplating': 'I am contemplating the future.',
            'meditating': 'I am meditating on the problem.',
            'pondering': 'I am pondering the question.',
            'wondering': 'I am wondering about the answer.',
            'questioning': 'I am questioning the decision.',
            'doubting': 'I am doubting the result.',
            'suspecting': 'I am suspecting the worst.',
            'trusting': 'I am trusting the process.',
            'believing': 'I am believing in myself.',
            'hoping': 'I am hoping for the best.',
            'wishing': 'I am wishing upon a star.',
            'dreaming': 'I am dreaming big.',
            'aspiring': 'I am aspiring to greatness.',
            'striving': 'I am striving for excellence.',
            'endeavoring': 'I am endeavoring to improve.',
            'attempting': 'I am attempting the task.',
            'trying': 'I am trying my best.',
            'struggling': 'I am struggling with the problem.',
            'failing': 'I am failing the test.',
            'succeeding': 'I am succeeding in my goals.',
            'winning': 'I am winning the game.',
            'losing': 'I am losing the match.',
            'tying': 'I am tying the game.',
            'competing': 'I am competing in the race.',
            'racing': 'I am racing against time.',
            'rushing': 'I am rushing to the finish.',
            'hurrying': 'I am hurrying to school.',
            'speeding': 'I am speeding up.',
            'slowing': 'I am slowing down.',
            'stopping': 'I am stopping the car.',
            'halting': 'I am halting the train.',
            'pausing': 'I am pausing the video.',
            'waiting': 'I am waiting for the bus.',
            'delaying': 'I am delaying the trip.',
            'postponing': 'I am postponing the meeting.',
            'canceling': 'I am canceling the order.',
            'aborting': 'I am aborting the mission.',
            'terminating': 'I am terminating the contract.',
            'ending': 'I am ending the relationship.',
            'completing': 'I am completing the project.',
            'finishing': 'I am finishing the work.',
            'concluding': 'I am concluding the speech.',
            'closing': 'I am closing the meeting.',
            'opening': 'I am opening the ceremony.',
            'beginning': 'I am beginning the journey.',
            'starting': 'I am starting the engine.',
            'launching': 'I am launching the rocket.',
            'initiating': 'I am initiating the program.',
            'commencing': 'I am commencing the operation.',
            'inaugurating': 'I am inaugurating the event.',
            'celebrating': 'I am celebrating the victory.',
            'honoring': 'I am honoring the heroes.',
            'remembering': 'I am remembering the fallen.',
            'memorializing': 'I am memorializing the occasion.',
            'commemorating': 'I am commemorating the anniversary.',
        }
        if w in adj_forms:
            return adj_forms[w]
        return f'This is very {w}.'

    # 副词
    if 'adv.' in pl:
        adv_forms = {
            'very': 'I am very happy.',
            'quite': 'I am quite sure.',
            'really': 'I really like it.',
            'always': 'I always get up early.',
            'often': 'I often read books.',
            'sometimes': 'I sometimes go swimming.',
            'never': 'I never eat meat.',
            'quickly': 'I finish quickly.',
            'slowly': 'I walk slowly.',
            'carefully': 'I listen carefully.',
            'easily': 'I solve it easily.',
            'here': 'Come here, please.',
            'there': 'Go there, please.',
            'now': 'I am studying now.',
            'then': 'I will go then.',
            'today': 'I am happy today.',
            'tomorrow': 'See you tomorrow.',
            'soon': 'I will be back soon.',
            'already': 'I have already finished.',
            'also': 'I also like it.',
            'too': 'I like it too.',
            'especially': 'I especially like math.',
            'actually': 'I actually know the answer.',
            'probably': 'I will probably go.',
            'perhaps': 'I will perhaps come.',
            'certainly': 'I will certainly help.',
            'definitely': 'I will definitely come.',
            'surely': 'I will surely remember.',
            'clearly': 'I clearly understand.',
            'simply': 'I simply love it.',
            'merely': 'I merely stated the fact.',
            'hardly': 'I hardly know him.',
            'barely': 'I barely passed the test.',
            'nearly': 'I nearly forgot.',
            'just': 'I just finished.',
            'only': 'I only eat vegetables.',
            'even': 'I even dance.',
            'still': 'I am still waiting.',
            'yet': 'I have not finished yet.',
            'again': 'I will try again.',
            'once': 'I have been there once.',
            'twice': 'I have been there twice.',
            'often': 'I often go there.',
            'seldom': 'I seldom go there.',
            'rarely': 'I rarely watch TV.',
            'occasionally': 'I occasionally go fishing.',
            'constantly': 'I am constantly learning.',
            'continually': 'I am continually improving.',
            'frequently': 'I frequently visit my grandparents.',
            'regularly': 'I regularly exercise.',
            'daily': 'I read daily.',
            'weekly': 'I play soccer weekly.',
            'monthly': 'I clean my room monthly.',
            'yearly': 'I visit my aunt yearly.',
            'forever': 'I will love you forever.',
            'always': 'I will always remember.',
            'never': 'I will never forget.',
            'immediately': 'I will come immediately.',
            'instantly': 'I will reply instantly.',
            'promptly': 'I will respond promptly.',
            'eventually': 'I will eventually succeed.',
            'ultimately': 'I will ultimately achieve my goal.',
            'finally': 'I have finally finished.',
            'lately': 'I have been busy lately.',
            'recently': 'I recently started a new job.',
            'currently': 'I am currently studying.',
            'presently': 'I will be there presently.',
            'shortly': 'I will arrive shortly.',
            'briefly': 'I will explain briefly.',
            'quickly': 'I will finish quickly.',
            'slowly': 'I will read slowly.',
            'carefully': 'I will listen carefully.',
            'thoughtfully': 'I will think thoughtfully.',
            'seriously': 'I will take it seriously.',
            'sincerely': 'I will help you sincerely.',
            'honestly': 'I will tell you honestly.',
            'truly': 'I truly believe in you.',
            'deeply': 'I deeply care about you.',
            'strongly': 'I strongly support you.',
            'highly': 'I highly recommend it.',
            'greatly': 'I greatly appreciate it.',
            'immensely': 'I immensely enjoy it.',
            'enormously': 'I enormously benefit from it.',
            'vastly': 'I vastly prefer this.',
            'considerably': 'I consider it considerably.',
            'significantly': 'It improves significantly.',
            'remarkably': 'It grows remarkably.',
            'exceptionally': 'She performs exceptionally.',
            'extraordinarily': 'He works extraordinarily.',
            'particularly': 'I particularly like this one.',
            'specifically': 'I specifically asked for this.',
            'generally': 'I generally agree.',
            'broadly': 'I broadly support the idea.',
            'widely': 'It is widely known.',
            'commonly': 'It is commonly used.',
            'typically': 'I typically wake up early.',
            'normally': 'I normally eat breakfast.',
            'usually': 'I usually go to school.',
            'traditionally': 'We traditionally celebrate it this way.',
            'historically': 'It is historically significant.',
            'scientifically': 'It is scientifically proven.',
            'technically': 'It is technically correct.',
            'logically': 'It logically follows.',
            'obviously': 'It is obviously true.',
            'clearly': 'It is clearly visible.',
            'evidently': 'It is evidently important.',
            'apparently': 'It is apparently true.',
            'seemingly': 'It is seemingly simple.',
            'relatively': 'It is relatively easy.',
            'comparatively': 'It is comparatively better.',
            'proportionally': 'It increases proportionally.',
            'approximately': 'It costs approximately 100.',
            'roughly': 'It weighs roughly 50 kg.',
            'nearly': 'I nearly finished.',
            'almost': 'I almost forgot.',
            'virtually': 'It is virtually done.',
            'practically': 'It is practically finished.',
            'essentially': 'It is essentially correct.',
            'fundamentally': 'It is fundamentally sound.',
            'basically': 'I basically understand.',
            'mainly': 'I mainly eat vegetables.',
            'primarily': 'I primarily study English.',
            'chiefly': 'I chiefly focus on math.',
            'principally': 'I principally work from home.',
            'largely': 'I largely agree.',
            'mostly': 'I mostly read fiction.',
            'predominantly': 'I predominantly listen to pop.',
            'exclusively': 'I exclusively eat organic food.',
            'solely': 'I solely depend on myself.',
            'entirely': 'I entirely agree.',
            'completely': 'I completely understand.',
            'totally': 'I totally agree.',
            'absolutely': 'I absolutely love it.',
            'utterly': 'I am utterly amazed.',
            'perfectly': 'It fits perfectly.',
            'exactly': 'It is exactly right.',
            'precisely': 'It is precisely what I need.',
            'quite': 'It is quite good.',
            'rather': 'It is rather cold.',
            'somewhat': 'It is somewhat difficult.',
            'fairly': 'It is fairly easy.',
            'moderately': 'It is moderately priced.',
            'reasonably': 'It is reasonably priced.',
            'sufficiently': 'It is sufficiently large.',
            'adequately': 'It is adequately prepared.',
            'appropriately': 'It is appropriately sized.',
            'suitably': 'It is suitably arranged.',
            'fittingly': 'It is fittingly decorated.',
            'aptly': 'It is aptly named.',
            'correctly': 'It is correctly answered.',
            'accurately': 'It is accurately measured.',
            'precisely': 'It is precisely calculated.',
            'exactly': 'It is exactly measured.',
            'rightly': 'I rightly deserve this.',
            'justly': 'I am justly rewarded.',
            'fairly': 'I am fairly treated.',
            'equitably': 'I am equitably treated.',
            'impartially': 'I am impartially judged.',
            'objectively': 'It is objectively true.',
            'subjectively': 'It is subjectively beautiful.',
            'personally': 'I personally prefer this.',
            'privately': 'I privately enjoy this.',
            'publicly': 'I publicly announce this.',
            'officially': 'I officially declare this.',
            'formally': 'I formally request this.',
            'informally': 'I informally suggest this.',
            'casually': 'I casually mention this.',
            'seriously': 'I seriously consider this.',
            'gravely': 'I gravely underestimate this.',
            'severely': 'I severely criticize this.',
            'harshly': 'I harshly judge this.',
            'strictly': 'I strictly enforce this.',
            'tightly': 'I tightly hold this.',
            'loosely': 'I loosely interpret this.',
            'freely': 'I freely choose this.',
            'willingly': 'I willingly accept this.',
            'reluctantly': 'I reluctantly agree.',
            'hesitantly': 'I hesitantly approve.',
            'eagerly': 'I eagerly await this.',
            'enthusiastically': 'I enthusiastically support this.',
            'passionately': 'I passionately pursue this.',
            'ardently': 'I ardently desire this.',
            'fervently': 'I fervently hope for this.',
            'earnestly': 'I earnestly pray for this.',
            'sincerely': 'I sincerely appreciate this.',
            'heartily': 'I heartily congratulate you.',
            'warmly': 'I warmly welcome you.',
            'kindly': 'I kindly remind you.',
            'gently': 'I gently touch the flower.',
            'softly': 'I softly whisper the words.',
            'quietly': 'I quietly read the book.',
            'silently': 'I silently pray.',
            'mutely': 'I mutely accept this.',
            'dumbly': 'I dumbly stare at this.',
            'blankly': 'I blankly look at this.',
            'vacantly': 'I vacantly gaze at this.',
            'absently': 'I absently nod my head.',
            'distantly': 'I distantly remember this.',
            'faintly': 'I faintly recall this.',
            'dimly': 'I dimly see the light.',
            'brightly': 'The sun shines brightly.',
            'clearly': 'The sky is clearly blue.',
            'vividly': 'I vividly remember this.',
            'sharply': 'I sharply focus on this.',
            'keenly': 'I keenly observe this.',
            'intently': 'I intently watch this.',
            'closely': 'I closely examine this.',
            'attentively': 'I attentively listen.',
            'carefully': 'I carefully read this.',
            'diligently': 'I diligently study.',
            'industriously': 'I industriously work.',
            'laboriously': 'I laboriously practice.',
            'assiduously': 'I assiduously train.',
            'sedulously': 'I sedulously improve.',
            'meticulously': 'I meticulously plan.',
            'thoroughly': 'I thoroughly check this.',
            'exhaustively': 'I exhaustively research this.',
            'comprehensively': 'I comprehensively understand this.',
            'fully': 'I fully support this.',
            'wholly': 'I wholly agree.',
            'entirely': 'I entirely approve.',
            'completely': 'I completely accept this.',
            'totally': 'I totally endorse this.',
            'utterly': 'I utterly reject this.',
            'absolutely': 'I absolutely deny this.',
            'categorically': 'I categorically refuse this.',
            'emphatically': 'I emphatically state this.',
            'forcefully': 'I forcefully argue this.',
            'strongly': 'I strongly oppose this.',
            'firmly': 'I firmly believe this.',
            'steadfastly': 'I steadfastly maintain this.',
            'resolutely': 'I resolutely decide this.',
            'determinedly': 'I determinedly pursue this.',
            'unwaveringly': 'I unwaveringly support this.',
            'unfailingly': 'I unfailingly deliver this.',
            'unhesitatingly': 'I unhesitatingly accept this.',
            'unquestioningly': 'I unquestioningly obey this.',
            'unconditionally': 'I unconditionally love you.',
            'invariably': 'I invariably arrive on time.',
            'consistently': 'I consistently improve.',
            'dependably': 'I dependably complete tasks.',
            'reliably': 'I reliably deliver results.',
            'trustworthily': 'I trustworthily handle secrets.',
            'faithfully': 'I faithfully serve you.',
            'loyally': 'I loyally support you.',
            'devotedly': 'I devotedly care for you.',
            'dedicatedly': 'I dedicatedly work on this.',
            'committing': 'I committing to this task.',
            'wholeheartedly': 'I wholeheartedly agree.',
            'sincerely': 'I sincerely thank you.',
        }
        if w in adv_forms:
            return adv_forms[w]
        return f'I do it {w}.'

    # 名词（默认）
    noun_forms = {
        'water': 'I drink water every day.',
        'food': 'I eat food every day.',
        'book': 'This is my book.',
        'pen': 'This is my pen.',
        'dog': 'I have a dog.',
        'cat': 'I have a cat.',
        'apple': 'I like apples.',
        'house': 'This is my house.',
        'school': 'I go to school every day.',
        'friend': 'She is my friend.',
        'teacher': 'He is my teacher.',
        'time': 'I have a good time.',
        'day': 'I have a good day.',
        'life': 'Life is beautiful.',
        'world': 'The world is big.',
        'problem': 'This is a big problem.',
        'idea': 'I have a good idea.',
        'game': 'I like this game.',
        'movie': 'I like this movie.',
        'story': 'I like this story.',
        'word': 'This is a new word.',
        'color': 'I like this color.',
        'city': 'I live in this city.',
        'country': 'I love my country.',
        'river': 'The river is long.',
        'mountain': 'The mountain is high.',
        'sun': 'The sun is bright.',
        'moon': 'The moon is beautiful.',
        'star': 'The star is shining.',
        'sky': 'The sky is blue.',
        'tree': 'The tree is tall.',
        'flower': 'The flower is beautiful.',
        'hand': 'Raise your hand.',
        'eye': 'Close your eye.',
        'face': 'Wash your face.',
        'heart': 'Follow your heart.',
        'mind': 'Change your mind.',
        'word': 'This is a new word.',
        'sentence': 'Write a sentence.',
        'letter': 'Write a letter.',
        'page': 'Turn the page.',
        'chapter': 'Read the next chapter.',
        'section': 'Read this section.',
        'paragraph': 'Write a paragraph.',
        'essay': 'Write an essay.',
        'report': 'Write a report.',
        'article': 'Read this article.',
        'news': 'Watch the news.',
        'weather': 'The weather is nice.',
        'season': 'Spring is my favorite season.',
        'month': 'This month is busy.',
        'week': 'I have a busy week.',
        'hour': 'I study for an hour.',
        'minute': 'Wait a minute.',
        'second': 'I will be there in a second.',
        'moment': 'Enjoy the moment.',
        'memory': 'I have a good memory.',
        'dream': 'I have a dream.',
        'hope': 'I have hope.',
        'fear': 'I have no fear.',
        'anger': 'Control your anger.',
        'happiness': 'Happiness is important.',
        'sadness': 'Overcome your sadness.',
        'surprise': 'I have a surprise.',
        'success': 'I wish you success.',
        'failure': 'Failure is the mother of success.',
        'truth': 'Tell the truth.',
        'lie': 'Do not tell a lie.',
        'secret': 'I have a secret.',
        'promise': 'I make a promise.',
        'chance': 'I give you a chance.',
        'choice': 'Make a good choice.',
        'decision': 'I support your decision.',
        'mistake': 'Learn from your mistake.',
        'lesson': 'I learn a lesson.',
        'experience': 'I gain experience.',
        'knowledge': 'Knowledge is power.',
        'wisdom': 'Wisdom comes with age.',
        'courage': 'Courage is important.',
        'strength': 'Strength is power.',
        'energy': 'I have energy.',
        'health': 'Health is wealth.',
        'wealth': 'Wealth is not everything.',
        'love': 'Love is beautiful.',
        'peace': 'Peace is important.',
        'freedom': 'Freedom is precious.',
        'justice': 'Justice is blind.',
        'equality': 'Equality is important.',
        'family': 'I love my family.',
        'home': 'Home is sweet.',
        'country': 'I love my country.',
        'earth': 'Protect the earth.',
        'nature': 'Nature is beautiful.',
        'animal': 'I love animals.',
        'plant': 'I love plants.',
        'insect': 'I hate insects.',
        'bird': 'The bird can fly.',
        'fish': 'The fish can swim.',
        'flower': 'The flower smells good.',
        'tree': 'The tree gives shade.',
        'grass': 'The grass is green.',
        'forest': 'The forest is big.',
        'ocean': 'The ocean is deep.',
        'river': 'The river flows.',
        'lake': 'The lake is calm.',
        'mountain': 'The mountain is high.',
        'valley': 'The valley is deep.',
        'desert': 'The desert is dry.',
        'island': 'The island is small.',
        'beach': 'The beach is sandy.',
        'sea': 'The sea is salty.',
        'wave': 'The wave is big.',
        'wind': 'The wind is strong.',
        'rain': 'The rain is heavy.',
        'snow': 'The snow is white.',
        'ice': 'The ice is cold.',
        'fire': 'The fire is hot.',
        'earth': 'The earth is round.',
        'air': 'The air is fresh.',
        'light': 'The light is bright.',
        'dark': 'The dark is scary.',
        'sound': 'The sound is loud.',
        'music': 'The music is nice.',
        'song': 'I like this song.',
        'dance': 'I like this dance.',
        'art': 'I like art.',
        'color': 'I like colors.',
        'shape': 'I like shapes.',
        'size': 'What size is it?',
        'length': 'The length is long.',
        'width': 'The width is wide.',
        'height': 'The height is tall.',
        'weight': 'The weight is heavy.',
        'speed': 'The speed is fast.',
        'time': 'Time is money.',
        'place': 'This is a good place.',
        'space': 'Space is big.',
        'distance': 'The distance is far.',
        'direction': 'Which direction is it?',
        'position': 'What position are you?',
        'location': 'Where is the location?',
        'area': 'This area is big.',
        'region': 'This region is beautiful.',
        'zone': 'This zone is safe.',
        'center': 'The center is here.',
        'edge': 'The edge is sharp.',
        'corner': 'Turn the corner.',
        'side': 'Which side are you on?',
        'front': 'In front of the house.',
        'back': 'At the back of the room.',
        'top': 'At the top of the mountain.',
        'bottom': 'At the bottom of the sea.',
        'inside': 'Look inside the box.',
        'outside': 'Play outside.',
        'surface': 'The surface is smooth.',
        'middle': 'In the middle of the road.',
        'part': 'This is my part.',
        'whole': 'The whole story.',
        'piece': 'Give me a piece.',
        'bit': 'Wait a bit.',
        'lot': 'I have a lot of books.',
        'some': 'I have some money.',
        'many': 'I have many friends.',
        'few': 'I have few enemies.',
        'all': 'I want all of them.',
        'none': 'I have none.',
        'each': 'Each one is different.',
        'every': 'Every day is a gift.',
        'both': 'Both are good.',
        'either': 'Either is fine.',
        'neither': 'Neither is good.',
        'other': 'The other one is better.',
        'another': 'Give me another chance.',
        'next': 'I will see you next week.',
        'last': 'I saw him last year.',
        'first': 'I was the first one.',
        'second': 'I came in second place.',
        'third': 'This is the third time.',
        'fourth': 'Turn left at the fourth corner.',
        'fifth': 'I live on the fifth floor.',
        'tenth': 'I finished in tenth place.',
        'hundred': 'I have a hundred books.',
        'thousand': 'There are a thousand people.',
        'million': 'A million stars.',
        'billion': 'A billion dollars.',
        'number': 'What is your number?',
        'amount': 'The amount is big.',
        'quantity': 'The quantity is large.',
        'quality': 'The quality is good.',
        'value': 'The value is high.',
        'price': 'What is the price?',
        'cost': 'The cost is low.',
        'money': 'I need money.',
        'cash': 'I pay cash.',
        'coin': 'I found a coin.',
        'note': 'I have a ten-dollar note.',
        'bill': 'I will pay the bill.',
        'tax': 'I pay tax.',
        'debt': 'I owe a debt.',
        'loan': 'I have a loan.',
        'salary': 'I get my salary.',
        'wage': 'I earn a wage.',
        'income': 'My income is good.',
        'profit': 'I made a profit.',
        'loss': 'I suffered a loss.',
        'budget': 'I have a budget.',
        'expense': 'The expense is high.',
        'savings': 'I have savings.',
        'investment': 'I have an investment.',
        'stock': 'I bought stock.',
        'share': 'I own a share.',
        'bond': 'I bought a bond.',
        'fund': 'I have a fund.',
        'account': 'I have an account.',
        'bank': 'I go to the bank.',
        'business': 'I run a business.',
        'company': 'I work for a company.',
        'office': 'I work in an office.',
        'factory': 'I work in a factory.',
        'shop': 'I go to the shop.',
        'store': 'I go to the store.',
        'market': 'I go to the market.',
        'supermarket': 'I go to the supermarket.',
        'restaurant': 'I eat at a restaurant.',
        'hotel': 'I stay at a hotel.',
        'hospital': 'I go to the hospital.',
        'school': 'I go to school.',
        'university': 'I go to university.',
        'library': 'I go to the library.',
        'museum': 'I go to the museum.',
        'theater': 'I go to the theater.',
        'cinema': 'I go to the cinema.',
        'park': 'I play in the park.',
        'garden': 'I have a garden.',
        'zoo': 'I go to the zoo.',
        'pool': 'I swim in the pool.',
        'beach': 'I go to the beach.',
        'mountain': 'I climb the mountain.',
        'forest': 'I walk in the forest.',
        'river': 'I fish in the river.',
        'lake': 'I swim in the lake.',
        'ocean': 'I sail on the ocean.',
        'sea': 'I swim in the sea.',
        'island': 'I live on an island.',
        'country': 'I visit the country.',
        'city': 'I live in the city.',
        'town': 'I live in a town.',
        'village': 'I live in a village.',
        'street': 'I walk on the street.',
        'road': 'I drive on the road.',
        'highway': 'I drive on the highway.',
        'bridge': 'I cross the bridge.',
        'tunnel': 'I drive through the tunnel.',
        'airport': 'I go to the airport.',
        'station': 'I go to the station.',
        'port': 'I go to the port.',
        'harbor': 'I go to the harbor.',
        'dock': 'I go to the dock.',
        'terminal': 'I go to the terminal.',
        'gate': 'I go through the gate.',
        'door': 'I open the door.',
        'window': 'I close the window.',
        'wall': 'I lean against the wall.',
        'floor': 'I clean the floor.',
        'ceiling': 'I paint the ceiling.',
        'roof': 'I fix the roof.',
        'stair': 'I climb the stairs.',
        'elevator': 'I take the elevator.',
        'escalator': 'I take the escalator.',
        'lift': 'I take the lift.',
        'corridor': 'I walk down the corridor.',
        'hall': 'I walk through the hall.',
        'room': 'I clean the room.',
        'kitchen': 'I cook in the kitchen.',
        'bathroom': 'I wash in the bathroom.',
        'bedroom': 'I sleep in the bedroom.',
        'living room': 'I sit in the living room.',
        'dining room': 'I eat in the dining room.',
        'garden': 'I play in the garden.',
        'garage': 'I park in the garage.',
        'basement': 'I play in the basement.',
        'attic': 'I store things in the attic.',
        'closet': 'I hang clothes in the closet.',
        'drawer': 'I put things in the drawer.',
        'shelf': 'I put books on the shelf.',
        'table': 'I eat at the table.',
        'chair': 'I sit on the chair.',
        'bed': 'I sleep on the bed.',
        'sofa': 'I sit on the sofa.',
        'couch': 'I sit on the couch.',
        'carpet': 'I walk on the carpet.',
        'curtain': 'I close the curtain.',
        'blanket': 'I use a blanket.',
        'pillow': 'I use a pillow.',
        'sheet': 'I change the sheet.',
        'towel': 'I dry with a towel.',
        'soap': 'I wash with soap.',
        'shampoo': 'I wash with shampoo.',
        'toothbrush': 'I brush with a toothbrush.',
        'toothpaste': 'I brush with toothpaste.',
        'comb': 'I comb my hair.',
        'brush': 'I brush my hair.',
        'mirror': 'I look in the mirror.',
        'sink': 'I wash in the sink.',
        'bathtub': 'I bath in the bathtub.',
        'shower': 'I take a shower.',
        'toilet': 'I use the toilet.',
        'tissue': 'I use a tissue.',
        'paper': 'I write on paper.',
        'pencil': 'I write with a pencil.',
        'pen': 'I write with a pen.',
        'eraser': 'I erase with an eraser.',
        'ruler': 'I measure with a ruler.',
        'scissors': 'I cut with scissors.',
        'knife': 'I cut with a knife.',
        'fork': 'I eat with a fork.',
        'spoon': 'I eat with a spoon.',
        'plate': 'I eat from a plate.',
        'bowl': 'I eat from a bowl.',
        'cup': 'I drink from a cup.',
        'glass': 'I drink from a glass.',
        'bottle': 'I drink from a bottle.',
        'can': 'I drink from a can.',
        'mug': 'I drink from a mug.',
        'pot': 'I cook in a pot.',
        'pan': 'I cook in a pan.',
        'oven': 'I cook in an oven.',
        'microwave': 'I heat in a microwave.',
        'refrigerator': 'I store in the refrigerator.',
        'freezer': 'I freeze in the freezer.',
        'stove': 'I cook on the stove.',
        'burner': 'I cook on the burner.',
        'fire': 'I warm by the fire.',
        'light': 'I turn on the light.',
        'lamp': 'I turn on the lamp.',
        'switch': 'I flip the switch.',
        'plug': 'I plug in the plug.',
        'socket': 'I plug into the socket.',
        'wire': 'I connect the wire.',
        'cable': 'I connect the cable.',
        'battery': 'I charge the battery.',
        'charger': 'I use the charger.',
        'computer': 'I use the computer.',
        'laptop': 'I use the laptop.',
        'tablet': 'I use the tablet.',
        'phone': 'I use the phone.',
        'television': 'I watch television.',
        'radio': 'I listen to the radio.',
        'speaker': 'I listen to the speaker.',
        'headphone': 'I listen with headphones.',
        'microphone': 'I speak into the microphone.',
        'camera': 'I take a photo with a camera.',
        'photo': 'I take a photo.',
        'picture': 'I draw a picture.',
        'image': 'I see an image.',
        'video': 'I watch a video.',
        'movie': 'I watch a movie.',
        'game': 'I play a game.',
        'sport': 'I play a sport.',
        'ball': 'I throw the ball.',
        'bat': 'I hit with a bat.',
        'net': 'I catch with a net.',
        'goal': 'I score a goal.',
        'point': 'I score a point.',
        'score': 'I keep score.',
        'team': 'I play on a team.',
        'player': 'I am a player.',
        'coach': 'He is my coach.',
        'fan': 'I am a fan.',
        'audience': 'The audience is big.',
        'crowd': 'The crowd is loud.',
        'race': 'I run in a race.',
        'competition': 'I enter a competition.',
        'contest': 'I enter a contest.',
        'match': 'I watch a match.',
        'tournament': 'I enter a tournament.',
        'championship': 'I win the championship.',
        'medal': 'I win a medal.',
        'trophy': 'I win a trophy.',
        'prize': 'I win a prize.',
        'award': 'I receive an award.',
        'gift': 'I give a gift.',
        'present': 'I give a present.',
        'surprise': 'I have a surprise.',
        'celebration': 'I have a celebration.',
        'party': 'I have a party.',
        'festival': 'I celebrate a festival.',
        'holiday': 'I have a holiday.',
        'vacation': 'I have a vacation.',
        'trip': 'I go on a trip.',
        'journey': 'I go on a journey.',
        'travel': 'I love to travel.',
        'adventure': 'I have an adventure.',
        'exploration': 'I go on an exploration.',
        'expedition': 'I go on an expedition.',
        'tour': 'I go on a tour.',
        'visit': 'I go on a visit.',
        'guest': 'I have a guest.',
        'host': 'I am the host.',
        'visitor': 'I have a visitor.',
        'tourist': 'I am a tourist.',
        'traveler': 'I am a traveler.',
        'passenger': 'I am a passenger.',
        'driver': 'I am the driver.',
        'pilot': 'I am the pilot.',
        'captain': 'I am the captain.',
        'sailor': 'I am a sailor.',
        'soldier': 'I am a soldier.',
        'officer': 'I am an officer.',
        'police': 'I call the police.',
        'fireman': 'I call the fireman.',
        'doctor': 'I see the doctor.',
        'nurse': 'I see the nurse.',
        'dentist': 'I see the dentist.',
        'teacher': 'I see the teacher.',
        'student': 'I am a student.',
        'classmate': 'He is my classmate.',
        'principal': 'I see the principal.',
        'professor': 'I see the professor.',
        'scientist': 'I am a scientist.',
        'engineer': 'I am an engineer.',
        'artist': 'I am an artist.',
        'musician': 'I am a musician.',
        'writer': 'I am a writer.',
        'painter': 'I am a painter.',
        'actor': 'I am an actor.',
        'actress': 'I am an actress.',
        'director': 'I am a director.',
        'designer': 'I am a designer.',
        'photographer': 'I am a photographer.',
        'journalist': 'I am a journalist.',
        'reporter': 'I am a reporter.',
        'lawyer': 'I am a lawyer.',
        'judge': 'I am a judge.',
        'businessman': 'I am a businessman.',
        'worker': 'I am a worker.',
        'farmer': 'I am a farmer.',
        'chef': 'I am a chef.',
        'waiter': 'I am a waiter.',
        'waitress': 'I am a waitress.',
        'cashier': 'I am a cashier.',
        'clerk': 'I am a clerk.',
        'secretary': 'I am a secretary.',
        'manager': 'I am a manager.',
        'boss': 'He is my boss.',
        'leader': 'I am a leader.',
        'president': 'I am the president.',
        'king': 'I am the king.',
        'queen': 'I am the queen.',
        'prince': 'I am the prince.',
        'princess': 'I am the princess.',
        'hero': 'He is a hero.',
        'villain': 'He is a villain.',
        'character': 'I am a character.',
        'person': 'I am a person.',
        'people': 'People are nice.',
        'human': 'I am a human.',
        'man': 'I am a man.',
        'woman': 'I am a woman.',
        'boy': 'I am a boy.',
        'girl': 'I am a girl.',
        'baby': 'I have a baby.',
        'child': 'I am a child.',
        'teenager': 'I am a teenager.',
        'adult': 'I am an adult.',
        'senior': 'I am a senior.',
        'elder': 'I respect my elders.',
        'parent': 'I love my parents.',
        'mother': 'I love my mother.',
        'father': 'I love my father.',
        'sister': 'I have a sister.',
        'brother': 'I have a brother.',
        'grandmother': 'I love my grandmother.',
        'grandfather': 'I love my grandfather.',
        'aunt': 'I love my aunt.',
        'uncle': 'I love my uncle.',
        'cousin': 'I have a cousin.',
        'nephew': 'I have a nephew.',
        'niece': 'I have a niece.',
        'friend': 'He is my friend.',
        'neighbor': 'He is my neighbor.',
        'stranger': 'Do not talk to strangers.',
        'enemy': 'He is my enemy.',
        'partner': 'She is my partner.',
        'colleague': 'He is my colleague.',
        'customer': 'He is a customer.',
        'client': 'He is a client.',
        'patient': 'He is a patient.',
        'student': 'He is a student.',
        'teacher': 'She is a teacher.',
        'doctor': 'He is a doctor.',
        'nurse': 'She is a nurse.',
        'lawyer': 'He is a lawyer.',
        'engineer': 'She is an engineer.',
        'scientist': 'He is a scientist.',
        'artist': 'She is an artist.',
        'musician': 'He is a musician.',
        'writer': 'She is a writer.',
        'actor': 'He is an actor.',
        'actress': 'She is an actress.',
        'athlete': 'He is an athlete.',
        'singer': 'She is a singer.',
        'dancer': 'He is a dancer.',
        'painter': 'She is a painter.',
        'photographer': 'He is a photographer.',
        'journalist': 'She is a journalist.',
        'reporter': 'He is a reporter.',
        'designer': 'She is a designer.',
        'inventor': 'He is an inventor.',
        'explorer': 'She is an explorer.',
        'adventurer': 'He is an adventurer.',
        'warrior': 'She is a warrior.',
        'soldier': 'He is a soldier.',
        'officer': 'She is an officer.',
        'captain': 'He is a captain.',
        'leader': 'She is a leader.',
        'hero': 'He is a hero.',
        'champion': 'She is a champion.',
        'winner': 'He is a winner.',
        'loser': 'She is a loser.',
        'giant': 'He is a giant.',
        'monster': 'It is a monster.',
        'ghost': 'It is a ghost.',
        'alien': 'It is an alien.',
        'robot': 'It is a robot.',
        'animal': 'It is an animal.',
        'pet': 'It is my pet.',
        'dog': 'It is a dog.',
        'cat': 'It is a cat.',
        'bird': 'It is a bird.',
        'fish': 'It is a fish.',
        'horse': 'It is a horse.',
        'cow': 'It is a cow.',
        'pig': 'It is a pig.',
        'sheep': 'It is a sheep.',
        'chicken': 'It is a chicken.',
        'duck': 'It is a duck.',
        'rabbit': 'It is a rabbit.',
        'mouse': 'It is a mouse.',
        'bear': 'It is a bear.',
        'tiger': 'It is a tiger.',
        'lion': 'It is a lion.',
        'elephant': 'It is an elephant.',
        'giraffe': 'It is a giraffe.',
        'monkey': 'It is a monkey.',
        'snake': 'It is a snake.',
        'frog': 'It is a frog.',
        'butterfly': 'It is a butterfly.',
        'bee': 'It is a bee.',
        'ant': 'It is an ant.',
        'spider': 'It is a spider.',
        'bug': 'It is a bug.',
        'insect': 'It is an insect.',
    }
    if w in noun_forms:
        return noun_forms[w]

    # 通用句型
    return f'I like this {w}.'


# ============================================================
# 五、主脚本
# ============================================================
def enrich_dict():
    js_path = r'E:\coding-zhou\AI 编程\记单词工具\js\dict.js'
    with open(js_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # 提取所有词条
    entries = re.findall(r'\{[^{}]+\}', content, re.DOTALL)
    enriched_entries = []
    stats = {'emoji': 0, 'root': 0, 'mnemonic': 0, 'example': 0}

    for entry in entries:
        word_m = re.search(r'word: "([^"]*)"', entry)
        pos_m = re.search(r'pos: "([^"]*)"', entry)
        meaning_m = re.search(r'meaning: "([^"]*)"', entry)

        if not word_m or not meaning_m:
            enriched_entries.append(entry)
            continue

        word = word_m.group(1)
        pos = pos_m.group(1) if pos_m else ''
        meaning = meaning_m.group(1)

        # 生成四个字段
        emoji = EMOJI.get(word, '')
        root = WORD_ROOTS.get(word, '')
        mnemonic = MNEMONICS.get(word, '')
        example = gen_example(word, pos, meaning)

        if emoji:
            stats['emoji'] += 1
        if root:
            stats['root'] += 1
        if mnemonic:
            stats['mnemonic'] += 1
        stats['example'] += 1

        # 注入字段
        new_entry = entry
        closing_brace = new_entry.rindex('}')
        before_brace = new_entry[:closing_brace].rstrip()

        # 确保 meaning 行末尾有逗号
        lines = before_brace.split('\n')
        if lines:
            last_line = lines[-1].rstrip()
            if last_line.endswith('"') and not last_line.endswith(','):
                lines[-1] = last_line + ','
            before_brace = '\n'.join(lines)

        fields = []
        if emoji:
            fields.append(f'    emoji: "{emoji}",')
        if root:
            fields.append(f'    root: "{root}",')
        if mnemonic:
            fields.append(f'    mnemonic: "{mnemonic}",')
        if example:
            fields.append(f'    example: "{example}",')

        if fields:
            # 去掉最后一个字段的逗号
            fields[-1] = fields[-1].rstrip(',')
            new_entry = before_brace + '\n' + '\n'.join(fields) + '\n  }'

        enriched_entries.append(new_entry)

    # 重组文件
    header = content[:content.index('const DICTIONARY = [')]
    new_content = header + 'const DICTIONARY = [\n' + ',\n'.join(enriched_entries) + '\n];\n'

    with open(js_path, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f'增强完成! 共 {len(enriched_entries)} 个词条')
    print(f'  emoji: {stats["emoji"]}')
    print(f'  词根: {stats["root"]}')
    print(f'  联想: {stats["mnemonic"]}')
    print(f'  例句: {stats["example"]}')


if __name__ == '__main__':
    enrich_dict()
